{{ config(materialized='table') }}
SELECT 
    REF.REF_AUTO_TERR_SK as REF_AUTO_TERR_SK,
    REF.END_EFF_DT as END_EFF_DT,
    REF.CHCKSUM as CHCKSUM,
    REF.CR_BY_MAPNG_ID as CR_BY_MAPNG_ID,
    REF.DW_CR_TMSP as DW_CR_TMSP,
    REF.UPD_BY_MAPNG_ID as UPD_BY_MAPNG_ID,
    REF.DW_UPD_TMSP as DW_UPD_TMSP,
    REF.WRK_FLOW_RUN_ID as WRK_FLOW_RUN_ID,
    REF.NISS_TERR_CD as NISS_TERR_CD,
    REF.CNTY_NM as CNTY_NM,
    REF.CITY_NM as CITY_NM,
    REF.SRC_EFF_DT as SRC_EFF_DT,
    REF.SRC_OBSLT_DT as SRC_OBSLT_DT,
    REF.NISS_ST_CD as NISS_ST_CD,
    REF.ST_ABBRV as ST_ABBRV,
    REF.ZIP_CD as ZIP_CD,
    REF.PP_COMMRCL_CD as PP_COMMRCL_CD
FROM {{ source('BIRP', 'RBI_REF_AUTO_TERR') }} REF
WHERE REF.END_EFF_DT='2999-12-31'
ORDER BY NISS_ST_CD, ST_ABBRV, ZIP_CD, PP_COMMRCL_CD