-- Purpose: Represents the expression transformation logic for various fields

WITH base_data AS (
  SELECT
    NISS_APRM_DETL_SK,
    ST_ABBR,
    ST_CD,
    RATNG_CMPY_CD,
    MLT_CAR_IND,
    RT_CLS,
    AGE,
    GENDR,
    MRTL_STAT,
    AUTO_USE_CD AS i_auto_use_cd,
    MILES_TO_WRK,
    GOOD_STDNT_IND,
    DRVR_TRNG_IND,
    SOI_TYP,
    ACCTNG_LOB,
    CVG_TYP_CD,
    NISS_CLASS_CD_FL
  FROM {{ ref('WRK_BIRP_NISS_APRM_DETL') }}
),
transformed_data AS (
  SELECT
    NISS_APRM_DETL_SK,
    ST_ABBR,
    ST_CD,
    RATNG_CMPY_CD,
    MLT_CAR_IND,
    RT_CLS,
    AGE,
    GENDR,
    MRTL_STAT,
    IIF(ISNULL(i_auto_use_cd), '', i_auto_use_cd) AS auto_use_cd,
    MILES_TO_WRK,
    GOOD_STDNT_IND,
    DRVR_TRNG_IND,
    SOI_TYP,
    ACCTNG_LOB,
    TO_INTEGER(AGE) AS iage,
    TO_INTEGER(MILES_TO_WRK) AS imiles_to_wrk,
    CVG_TYP_CD,
    NISS_CLASS_CD_FL,
    DECODE(CVG_TYP_CD, 'Indemnity', 'Indemnity_Class', 'Other', 'Other_Class') AS v_class_cd_indemnity,
    IIF(ST_ABBR = 'FL', NISS_CLASS_CD_FL, '') AS v_class_cd_auto_1a,
    IIF(MLT_CAR_IND = 'Y', 'Multi_Car_Class', 'Single_Car_Class') AS v_class_cd_auto_1,
    IIF(RT_CLS = 'A', 'Class_A', 'Class_B') AS v_class_cd_auto_2,
    IIF(GOOD_STDNT_IND = 'Y', 'Good_Student_Class', 'Regular_Class') AS v_class_cd_auto_3,
    IIF(DRVR_TRNG_IND = 'Y', 'Trained_Driver_Class', 'Untrained_Driver_Class') AS v_class_cd_auto_4,
    DECODE(SOI_TYP, 'Type1', 'Type1_Class', 'Type2', 'Type2_Class') AS v_class_cd_auto_5,
    IIF(ACCTNG_LOB = 'LOB1', DECODE(CVG_TYP_CD, 'TypeA', 'TypeA_Class', 'TypeB', 'TypeB_Class'), 'Default_Class') AS v_class_cd_auto_6
  FROM base_data
)

SELECT
  NISS_APRM_DETL_SK,
  ST_ABBR,
  ST_CD,
  RATNG_CMPY_CD,
  MLT_CAR_IND,
  RT_CLS,
  AGE,
  GENDR,
  MRTL_STAT,
  auto_use_cd,
  MILES_TO_WRK,
  GOOD_STDNT_IND,
  DRVR_TRNG_IND,
  SOI_TYP,
  ACCTNG_LOB,
  iage,
  imiles_to_wrk,
  CVG_TYP_CD,
  NISS_CLASS_CD_FL,
  v_class_cd_indemnity,
  v_class_cd_auto_1,
  v_class_cd_auto_1a,
  v_class_cd_auto_2,
  v_class_cd_auto_3,
  v_class_cd_auto_4,
  v_class_cd_auto_5,
  v_class_cd_auto_6
FROM transformed_data