{{ config(materialized='table') }}
SELECT 
    NISS_APRM_DETL_SK,
    ST_NM,
    ST_ABBR,
    LTRIM(RTRIM(ACCTNG_LOB)) ACCTNG_LOB,
    LTRIM(RTRIM(CVG_TYP_CD)) CVG_TYP_CD,
    LTRIM(RTRIM(CVG_AMT)) CVG_AMT,
    LTRIM(RTRIM(BI_LMT)) BI_LMT,
    LTRIM(RTRIM(GA_ADDED_AT_FAULT_IND)) GA_ADDED_AT_FAULT_IND,
    LTRIM(RTRIM(FA2_PLCY_IND)) FA2_PLCY_IND,
    LTRIM(RTRIM(UM_UMI_STACKING)) UM_UMI_STACKING,
    PIP_WVR_WL_IND,
    PIP_MED_SEC_IND,
    PIP_LOSS_INCOME_IND,
    MI_PPO_IND,
    LTRIM(RTRIM(RATNG_CMPY_CD)) RATNG_CMPY_CD,
    LTRIM(RTRIM(COMP_DED)) COMP_DED,
    LTRIM(RTRIM(COLL_DED)) COLL_DED,
    LTRIM(RTRIM(LOB)) MIS_LOB,
    LTRIM(RTRIM(SOURCE_IND_DERIVED)) SOURCE_IND_DERIVED
FROM {{ source('FDR', 'WRK_BIRP_NISS_APRM_DETL') }}
WHERE ST_ABBR NOT IN ('NY','NJ')