{{ config(materialized='table') }}
SELECT
    NISS_APRM_DETL_SK,
    ST_ABBR,
    ST_CD,
    RATNG_CMPY_CD,
    MLT_CAR_IND,
    RT_CLS,
    FINAL_RDRVR_AGE,
    GENDR,
    MRTL_STAT,
    AUTO_USE_CD,
    MILES_TO_WRK,
    GOOD_STDNT_IND,
    DRVR_TRNG_IND,
    SOI_TYP,
    ACCTNG_LOB,
    CVG_TYP_CD,
    CASE WHEN ST_ABBR='FL' AND FINAL_RDRVR_AGE!=' ' THEN 
        CASE 
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='N' AND (RIGHT(RT_CLS,1)='5' OR RT_CLS IN ('5M','9','5F','2F','2M')) AND MRTL_STAT='M' AND AUTO_USE_CD!='FRM' THEN '1620'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='N' AND (RIGHT(RT_CLS,1)='5' OR RT_CLS IN ('5M','9','5F','2F','2M')) AND MRTL_STAT='M' AND AUTO_USE_CD='FRM' THEN '1623'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='Y' AND (RIGHT(RT_CLS,1)='5' OR RT_CLS IN ('5M','9','5F','2F','2M')) AND MRTL_STAT='M' AND AUTO_USE_CD!='FRM' THEN '1622'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='Y' AND (RIGHT(RT_CLS,1)='5' OR RT_CLS IN ('5M','9','5F','2F','2M')) AND MRTL_STAT='M' AND AUTO_USE_CD='FRM' THEN '1621'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='N' AND (RIGHT(RT_CLS,1)='2' OR RT_CLS IN ('2M','9','5M','2F')) AND MRTL_STAT='S' AND AUTO_USE_CD!='FRM' THEN '1630'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='N' AND (RIGHT(RT_CLS,1)='2' OR RT_CLS IN ('2M','9','2F')) AND MRTL_STAT='S' AND AUTO_USE_CD='FRM' THEN '1633'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='Y' AND (RIGHT(RT_CLS,1)='2' OR RT_CLS IN ('2M','9','2F','5M')) AND (MRTL_STAT IN ('S','') OR MRTL_STAT IS NULL) AND AUTO_USE_CD!='FRM' THEN '1632'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='Y' AND (RIGHT(RT_CLS,1)='2' OR RT_CLS IN ('2M','9','2F','5M')) AND (MRTL_STAT IN ('S','') OR MRTL_STAT IS NULL) AND AUTO_USE_CD='FRM' THEN '1631'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='N' AND RT_CLS IN ('08','18','28','38','48','58','M6','M8','N6','N8','3','5F','2F','2M','9') AND AUTO_USE_CD!='FRM' THEN '1610'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='N' AND RT_CLS IN ('08','18','28','38','48','58','M6','M8','N6','N8','3','5F','2F','2M') AND AUTO_USE_CD='FRM' THEN '1613'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='Y' AND RT_CLS IN ('08','18','28','38','48','58','M6','M8','N6','N8','3','5F','2F','2M') AND AUTO_USE_CD!='FRM' THEN '1612'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='Y' AND RT_CLS IN ('08','18','28','38','48','58','M6','M8','N6','N8','3','5F','2F','2M') AND AUTO_USE_CD='FRM' THEN '1611'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='N' AND GENDR='F' AND AUTO_USE_CD!='FRM' THEN '1640'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='N' AND GENDR='F' AND AUTO_USE_CD='FRM' THEN '1643'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='Y' AND GENDR='F' AND AUTO_USE_CD!='FRM' THEN '1642'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='Y' AND GENDR='F' AND AUTO_USE_CD='FRM' THEN '1641'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>24 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<30 AND MLT_CAR_IND='N' AND (AUTO_USE_CD IN ('HOP','HPS','PLS','STG','COM','#') or AUTO_USE_CD!='FRM') THEN '1650'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>24 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<30 AND MLT_CAR_IND='N' AND AUTO_USE_CD IN ('FRM') THEN '1653'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>24 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<30 AND MLT_CAR_IND='Y' AND (AUTO_USE_CD IN ('HOP','HPS','PLS','STG','COM','#') or AUTO_USE_CD!='FRM') THEN '1652'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>24 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<30 AND MLT_CAR_IND='Y' AND AUTO_USE_CD IN ('FRM') THEN '1651'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND MLT_CAR_IND='N' AND AUTO_USE_CD IN ('FRM') THEN '1213'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND MLT_CAR_IND='N' AND AUTO_USE_CD IN ('HOP','HPS','PLS','STG','#') THEN '1210'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND MLT_CAR_IND='Y' AND AUTO_USE_CD IN ('HOP','HPS','PLS','STG','#') THEN '1212'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND MLT_CAR_IND='Y' AND AUTO_USE_CD IN ('FRM') THEN '1211'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND MLT_CAR_IND='N' AND AUTO_USE_CD IN ('COM') AND TO_NUMBER(MILES_TO_WRK, 38, 0)<10 THEN '1220'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND MLT_CAR_IND='Y' AND AUTO_USE_CD IN ('COM') AND TO_NUMBER(MILES_TO_WRK, 38, 0)<10 THEN '1222'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND MLT_CAR_IND='N' AND AUTO_USE_CD IN ('COM') AND TO_NUMBER(MILES_TO_WRK, 38, 0)>=10 THEN '1230'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND MLT_CAR_IND='Y' AND AUTO_USE_CD IN ('COM') AND TO_NUMBER(MILES_TO_WRK, 38, 0)>=10 THEN '1232'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND MLT_CAR_IND='N' AND AUTO_USE_CD NOT IN ('HOP','HPS','PLS','STG','#','FRM','COM') THEN '1400'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND MLT_CAR_IND='Y' AND AUTO_USE_CD NOT IN ('HOP','HPS','PLS','STG','#','FRM','COM') THEN '1402'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND MLT_CAR_IND='N' AND AUTO_USE_CD IN ('PLS','STG','#') THEN '1510'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND MLT_CAR_IND='N' AND AUTO_USE_CD IN ('COM') AND TO_NUMBER(MILES_TO_WRK, 38, 0)<10 THEN '1520'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND MLT_CAR_IND='N' AND AUTO_USE_CD IN ('COM') AND TO_NUMBER(MILES_TO_WRK, 38, 0)>=10 THEN '1530'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND MLT_CAR_IND='N' AND AUTO_USE_CD IN ('FRM') THEN '1513'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND MLT_CAR_IND='N' AND AUTO_USE_CD NOT IN ('PLS','STG','FRM','COM','#') THEN '1550'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND MLT_CAR_IND='Y' AND AUTO_USE_CD IN ('PLS','STG','#') THEN '1512'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND MLT_CAR_IND='Y' AND AUTO_USE_CD IN ('COM') AND TO_NUMBER(MILES_TO_WRK, 38, 0)<10 THEN '1522'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND MLT_CAR_IND='Y' AND AUTO_USE_CD IN ('COM') AND TO_NUMBER(MILES_TO_WRK, 38, 0)>=10 THEN '1532'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND MLT_CAR_IND='Y' AND AUTO_USE_CD IN ('FRM') THEN '1511'
            WHEN TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND MLT_CAR_IND='Y' AND AUTO_USE_CD NOT IN ('PLS','STG','FRM','COM','#') THEN '1552'
        END 
    ELSE '' 
    END as NISS_CLASS_CD_FL,
    REC_EXCPN_IND,
    REC_EXCPN_RSN_DESC
FROM (
    SELECT
        NISS_APRM_DETL_SK,
        LTRIM(RTRIM(ST_ABBR)) ST_ABBR,
        LTRIM(RTRIM(ST_CD)) ST_CD,
        LTRIM(RTRIM(RATNG_CMPY_CD)) RATNG_CMPY_CD,
        LTRIM(RTRIM(MLT_CAR_IND)) MLT_CAR_IND,
        LTRIM(RTRIM(RT_CLS)) RT_CLS,
        LTRIM(RTRIM(FINAL_RDRVR_AGE)) FINAL_RDRVR_AGE,
        LTRIM(RTRIM(GENDR)) GENDR,
        LTRIM(RTRIM(MRTL_STAT)) MRTL_STAT,
        LTRIM(RTRIM(AUTO_USE_CD)) AUTO_USE_CD,
        LTRIM(RTRIM(MILES_TO_WRK)) MILES_TO_WRK,
        LTRIM(RTRIM(GOOD_STDNT_IND)) GOOD_STDNT_IND,
        LTRIM(RTRIM(DRVR_TRNG_IND)) DRVR_TRNG_IND,
        LTRIM(RTRIM(SOI_TYP)) SOI_TYP,
        LTRIM(RTRIM(ACCTNG_LOB)) ACCTNG_LOB,
        LTRIM(RTRIM(CVG_TYP_CD)) CVG_TYP_CD,
        REC_EXCPN_IND,
        REC_EXCPN_RSN_DESC
    FROM {{ source('FDR', 'WRK_BIRP_NISS_APRM_DETL') }}
    WHERE ST_ABBR NOT IN ('NY','NJ') AND SOURCE_IND_DERIVED='FARMERS'
)
```

This code block contains the DBT models converted from the Informatica PowerCenter source definitions with SQL Override and Lookup SQL Override. Each model is configured to be materialized as a table and uses DBT functions to reference sources and variables. The SQL logic from the overrides is preserved, including any transformations and filters.