{{
  config(materialized='ephemeral')
}}

WITH source_data AS (
  SELECT * FROM {{ source('DBA_COMMON_UTILS', 'PRE_FDR_FIRE_PLCY_TRANS_RSLT') }}
),

upd_ABC_BAL_DETAIL_AMTS_RP_INSERT AS (
  SELECT
    BAL_ROW_COUNTS_SK,
    WRKFL_CMPNT_OBJ_ID,
    FIN_DETAIL_AMT,
    0 AS BAL_ROW_COUNTS_SK
  FROM source_data
),

upd_ABC_BAL_DETAIL_AMTS_SOURCE_INSERT AS (
  SELECT
    BAL_ROW_COUNTS_SK,
    WRKFL_CMPNT_OBJ_ID,
    FIN_DETAIL_AMT,
    0 AS BAL_ROW_COUNTS_SK
  FROM upd_ABC_BAL_DETAIL_AMTS_RP_INSERT
),

upd_ABC_BAL_DETAIL_AMTS_SOURCE_UPDATE AS (
  SELECT
    BAL_ROW_COUNTS_SK,
    WRKFL_CMPNT_OBJ_ID,
    FIN_DETAIL_AMT,
    0 AS BAL_ROW_COUNTS_SK
  FROM upd_ABC_BAL_DETAIL_AMTS_SOURCE_INSERT
),

upd_ABC_BAL_DETAIL_AMTS_TARGET_INSERT_UPDATE AS (
  SELECT
    BAL_ROW_COUNTS_SK,
    WRKFL_CMPNT_OBJ_ID,
    FIN_DETAIL_AMT,
    0 AS BAL_ROW_COUNTS_SK
  FROM upd_ABC_BAL_DETAIL_AMTS_SOURCE_UPDATE
),

upd_FACESHEET_DT AS (
  SELECT
    SRC_PLCY_ID_SK,
    SRC_INSERT_TRANS_TMSP,
    SRC_EFF_DT,
    BAL_ROW_COUNTS_SK,
    'DD_UPDATE' AS update_strategy
  FROM upd_ABC_BAL_DETAIL_AMTS_TARGET_INSERT_UPDATE
),

upd_INSERT AS (
  SELECT
    TFPLCY_TRAN_RESULT_SK1,
    LAT_DATE1,
    LAT_TIME1,
    BAL_ROW_COUNTS_SK,
    'DD_INSERT' AS insert_strategy
  FROM upd_FACESHEET_DT
),

upd_SOURCE_INSERT AS (
  SELECT
    BAL_ROW_COUNTS_SK,
    PROC_CD,
    o_RECRD_CNT_QTY,
    BAL_ROW_COUNTS_SK,
    'DD_INSERT' AS insert_strategy
  FROM upd_INSERT
),

upd_SOURCE_UPDATE_INSERT AS (
  SELECT
    TFPLCY_TRAN_RESULT_SK3,
    LAT_DATE3,
    LAT_TIME3,
    BAL_ROW_COUNTS_SK,
    'DD_INSERT' AS insert_strategy
  FROM upd_SOURCE_INSERT
),

upd_REPROC_INSERT AS (
  SELECT
    TFPLCY_TRAN_RESULT_SK4,
    LAT_DATE4,
    LAT_TIME4,
    BAL_ROW_COUNTS_SK,
    'DD_INSERT' AS insert_strategy
  FROM upd_SOURCE_UPDATE_INSERT
),

upd_INS_GATE_KPR AS (
  SELECT
    TFPLCY_TRAN_RESULT_SK6,
    SRC_SYS_HH_NUM6,
    SRC_TRANS_TMSP6,
    BAL_ROW_COUNTS_SK,
    'DD_INSERT' AS insert_strategy
  FROM upd_REPROC_INSERT
),

rtr_SPLITS AS (
  SELECT
    TFPLCY_TRAN_RESULT_SK1,
    LAT_DATE1,
    LAT_TIME1,
    BAL_ROW_COUNTS_SK,
    CASE
      WHEN INSERT_IND = 1 AND DUP_FLAG <> 1 THEN 'INSERT'
      ELSE 'DEFAULT'
    END AS split_group
  FROM upd_INS_GATE_KPR
)

SELECT * FROM rtr_SPLITS