-- Purpose: This model derives various class codes for Toggle Auto data based on state abbreviations, age, gender, marital status, and other factors.

WITH base_data AS (
    SELECT
        NISS_APRM_DETL_SK,
        ST_CD,
        ST_ABBR,
        ACCTNG_LOB,
        CVG_TYP_CD,
        RATNG_CMPY_CD,
        MLT_CAR_IND,
        AGE,
        GENDR,
        MRTL_STAT,
        i_AUTO_USE_CD,
        SOI_TYP,
        REC_EXCPN_IND,
        REC_EXCPN_RSN_DESC_ZIP
    FROM {{ ref('WRK_BIRP_NISS_APRM_DETL') }}
),
derived_data AS (
    SELECT
        NISS_APRM_DETL_SK,
        ST_CD,
        ST_ABBR,
        ACCTNG_LOB,
        CVG_TYP_CD,
        RATNG_CMPY_CD,
        MLT_CAR_IND,
        AGE,
        TO_INTEGER(AGE) AS IAGE,
        GENDR,
        MRTL_STAT,
        COALESCE(i_AUTO_USE_CD, '') AS AUTO_USE_CD,
        SOI_TYP,
        DECODE(SOI_TYP, 'A', 'Indemnity_A', 'B', 'Indemnity_B', 'C', 'Indemnity_C', NULL) AS v_CLASS_CD_Indemnity,
        IIF(ST_ABBR = 'FL', 'Toggle_FL', 'Toggle_Other') AS v_CLASS_CODE_TAuto,
        DECODE(v_CLASS_CODE_TAuto, 'Toggle_FL', 'FL_Class', 'Toggle_Other', 'Other_Class', NULL) AS v_CLASS_CODE_TAuto_Final,
        DECODE(ST_CD, 'NY', 'Secondary_NY', 'NJ', 'Secondary_NJ', NULL) AS v_CLASS_CODE_Secondary,
        DECODE(ACCTNG_LOB, 'LOB1', 'Misc_1_LOB1', 'LOB2', 'Misc_1_LOB2', NULL) AS v_CLASS_CD_Misc_1,
        DECODE(CVG_TYP_CD, 'Type1', 'Misc_2_Type1', 'Type2', 'Misc_2_Type2', NULL) AS v_CLASS_CD_Misc_2,
        IIF(MLT_CAR_IND = 'Y', 'Misc_3_MultiCar', 'Misc_3_SingleCar') AS v_CLASS_CD_Misc_3,
        IIF(GENDR = 'M', 'Misc_4_Male', 'Misc_4_Female') AS v_CLASS_CD_Misc_4,
        DECODE(MRTL_STAT, 'Single', 'Misc_5_Single', 'Married', 'Misc_5_Married', NULL) AS v_CLASS_CD_Misc_5,
        IIF(ST_ABBR = 'FL', DECODE(ACCTNG_LOB, 'LOB1', 'Misc_6_FL_LOB1', 'LOB2', 'Misc_6_FL_LOB2', NULL), NULL) AS v_CLASS_CD_Misc_6_FL,
        DECODE(v_CLASS_CD_Misc_6_FL, NULL, v_CLASS_CD_Misc_5, v_CLASS_CD_Misc_6_FL) AS v_CLASS_CD_Misc_Final,
        DECODE(v_CLASS_CODE_TAuto_Final, 'FL_Class', 'NISS_FL', 'Other_Class', 'NISS_Other', NULL) AS v_NISS_CLASS_CD,
        IIF(v_NISS_CLASS_CD IS NULL, 'Exception', NULL) AS REC_EXCP_IND,
        IIF(v_NISS_CLASS_CD IS NULL, 'Class Code Exception', NULL) AS REC_EXCP_DESC_CLASS
    FROM base_data
)
SELECT
    NISS_APRM_DETL_SK,
    ST_CD,
    ST_ABBR,
    ACCTNG_LOB,
    CVG_TYP_CD,
    RATNG_CMPY_CD,
    MLT_CAR_IND,
    AGE,
    IAGE,
    GENDR,
    MRTL_STAT,
    AUTO_USE_CD,
    SOI_TYP,
    v_CLASS_CD_Indemnity,
    v_CLASS_CODE_TAuto,
    v_CLASS_CODE_TAuto_Final,
    v_CLASS_CODE_Secondary,
    v_CLASS_CD_Misc_1,
    v_CLASS_CD_Misc_2,
    v_CLASS_CD_Misc_3,
    v_CLASS_CD_Misc_4,
    v_CLASS_CD_Misc_5,
    v_CLASS_CD_Misc_6_FL,
    v_CLASS_CD_Misc_Final,
    v_NISS_CLASS_CD,
    IIF(v_NISS_CLASS_CD IS NULL, REC_EXCPN_IND, 'N') AS REC_EXCPN_IND,
    IIF(v_NISS_CLASS_CD IS NULL, REC_EXCP_DESC_CLASS, REC_EXCPN_RSN_DESC_ZIP) AS REC_EXCP_DESC
FROM derived_data