version: 2

models:
  - name: fct_W_CLAIM_CD_BUR_SCD3_U
    description: This model performs an update operation on the W_CLAIM_CD_BUR_SCD3_U table using data from the intermediate update source.
    meta:
      owner: data_team
      domain: claims
    config:
      materialized: view
    tags: ['update', 'claims']
    columns: []

  - name: fct_W_CLAIM_CD_BUR_SCD3_I
    description: This model performs an insert operation on the W_CLAIM_CD_BUR_SCD3_I table, joining data from intermediate sources for claim insert updates.
    meta:
      owner: data_team
      domain: claims
    config:
      materialized: view
    tags: ['insert', 'claims']
    columns: []

  - name: fct_Output
    description: This model writes data to the target table using data from the intermediate source.
    meta:
      owner: data_team
      domain: output
    config:
      materialized: view
    tags: ['output', 'data_transfer']
    columns: []