{{ config(materialized='view') }}

SELECT
"SOI_ENH_SK" AS soi_enh_sk,
"PLCY_ID_SK" AS plcy_id_sk,
"SOI_ID" AS soi_id,
"SRC_TRANS_TMSP" AS src_trans_tmsp,
"SRC_EFF_DT" AS src_eff_dt,
"ON_OFF_PREM_TYP_RECRD" AS on_off_prem_typ_recrd,
"ADD_UNIT_IND" AS add_unit_ind,
"RPLC_VEH_IND" AS rplc_veh_ind,
"DISTNT_STDNT_DISC_IND" AS distnt_stdnt_disc_ind,
"AUTO_SPLTY_MTRC_DISC_IND" AS auto_splty_mtrc_disc_ind,
"AUTO_SPLTY_BOAT_WC_DISC_IND" AS auto_splty_boat_wc_disc_ind,
"AUTO_SPLTY_OFFRD_OTH_DISC_IND" AS auto_splty_offrd_oth_disc_ind,
"AUTO_SPLTY_MTRHM_TRLR_DISC_IND" AS auto_splty_mtrhm_trlr_disc_ind,
"DRVR_IMPRV_DISC_IND" AS drvr_imprv_disc_ind,
"DEFNS_DRVR_DISC_IND" AS defns_drvr_disc_ind,
"CR_BY_MAPNG_ID" AS cr_by_mapng_id,
"DW_CR_TMSP" AS dw_cr_tmsp,
"UPD_BY_MAPNG_ID" AS upd_by_mapng_id,
"DW_UPD_TMSP" AS dw_upd_tmsp,
"WRK_FLOW_RUN_ID" AS wrk_flow_run_id,
"LSE_VEH_IND" AS lse_veh_ind,
"MLT_LINE_DISC_DESC" AS mlt_line_disc_desc,
"PRD_TYP" AS prd_typ,
"AUTO_USE_CD" AS auto_use_cd,
"AUTO_USE_DESC" AS auto_use_desc,
"RT_CLS" AS rt_cls,
"FARM_DISC_CD" AS farm_disc_cd,
"NON_SMKR" AS non_smkr,
"FIRE_TAX_CD_CNTY" AS fire_tax_cd_cnty,
"FIRE_TAX_CD_CITY" AS fire_tax_cd_city,
"NEW_BUS_REINSTMT_DT" AS new_bus_reinstmt_dt,
"LMT_TORT" AS lmt_tort
FROM {{ source('staging', 'DIM_AG_SOI_ENH') }}