snowflake:
  outputs:
    dev:
      account: farmers-awsuseast2.privatelink
      database: DBA_COMMON_UTILS
      password: '#8,7qJU%36rF4>daA-DS'
      authenticator: https://farmersinsurance.okta.com
      role: FARMERS_OKTA_SFLAKE_DEV_IT_DATAECONOMY_RW
      schema: DBA
      threads: 1
      type: snowflake
      user: svc-dtecnmy-np-rw
      warehouse: DEV_IT_DATAECONOMY_WH
  target: dev
  