{{ config(materialized='table') }}
SELECT 
    NISS_APRM_DETL_SK, ST_NM, ST_ABBR, ACCTNG_LOB, LTRIM(RTRIM(CVG_TYP_CD)) CVG_TYP_CD, 
    LTRIM(RTRIM(CVG_AMT)) CVG_AMT, LTRIM(RTRIM(BI_LMT)) BI_LMT, PIP_LOSS_INCOME_IND, 
    LTRIM(RTRIM(COALESCE(PRD_GRP_CD,''))) PRD_GRP_CD, LTRIM(RTRIM(COALESCE(NJ_HLTH_INSR_PRIM,''))) NJ_HLTH_INSR_PRIM, 
    LTRIM(RTRIM(COALESCE(NJ_EXTR_PIP_PKG,''))) NJ_EXTR_PIP_PKG, NJ_RESDNC_RLTNSHP_PIP_IND, 
    NY_FULL_CVG_GLASS_COMP_IND, NY_SSL_IND, LTRIM(RTRIM(COMP_DED)) COMP_DED, 
    LTRIM(RTRIM(COLL_DED)) COLL_DED, REC_EXCPN_IND, REC_EXCPN_RSN_DESC
FROM {{ source('FDR', 'WRK_BIRP_NISS_APRM_DETL') }}
WHERE ST_ABBR IN ('NY','NJ')