-- Purpose: Reporting and analytics for NISS auto parameters
SELECT
    {{ dbt_utils.surrogate_key(['NISS_CMPNY_CD', 'REG_PER_YR', 'FISC_PER_YR']) }} AS niss_auto_atprm_sk,
    *
FROM {{ ref('int_NISS_AUTO_ATPRM_LND') }}

#### schema.yml
version: 2

models:
  - name: int_NISS_AUTO_ATPRM_LND
    description: Intermediate transformation for NISS auto parameters
    columns:
      - name: row_id
        description: Row ID generated by sequence
        tests:
          - not_null
          - unique

  - name: fct_NISS_AUTO_ATPRM
    description: Reporting and analytics for NISS auto parameters
    columns:
      - name: niss_auto_atprm_sk
        description: Surrogate key for NISS auto parameters
        tests:
          - not_null
          - unique

seeds:
  - name: NISS_STATE_LOOKUP
    description: Encodes state name to state code mapping
    columns:
      - name: FARMERS_STATE_NAME
        description: State Name
        tests:
          - not_null
          - unique
      - name: NISS_STATE_CODE
        description: State Code
        tests:
          - not_null
          - unique

sources:
  - name: power_center
    tables:
      - name: WRK_BIRP_TA_NISS_NU0C_APRM_LND
        columns:
          - name: PRINCIPAL_OPRT
            tests:
              - not_null
          - name: SOURCE_IND_DERIVED
            tests:
              - not_null
          - name: NISS_CMPNY_CD
            tests:
              - not_null
          - name: REG_PER_YR
            tests:
              - not_null
          - name: FISC_PER_YR
            tests:
              - not_null
          - name: NAIC_CMPNY_CD
            tests:
              - not_null
          - name: ST_NM
            tests:
              - not_null
          - name: ST_CD
            tests:
              - not_null
          - name: ACCTNG_LOB
            tests:
              - not_null
          - name: CVG_TYP_CD
            tests:
              - not_null
          - name: CVG_AMT
            tests:
              - not_null
          - name: BI_LMT
            tests:
              - not_null
          - name: GA_ADDED_AT_FAULT_IND
            tests:
              - not_null
          - name: PLCY_IND
            tests:
              - not_null
          - name: UM_UMI_STACKING
            tests:
              - not_null
          - name: PIP_WVR_WL_IND
            tests:
              - not_null
          - name: PIP_MED_SEC_IND
            tests:
              - not_null
          - name: PIP_LOSS_INCOME_IND
            tests:
              - not_null
          - name: MI_PPO_IND
            tests:
              - not_null
          - name: PRD_GRP_CD
            tests:
              - not_null
          - name: NJ_HLTH_INSR_PRIM
            tests:
              - not_null
          - name: NJ_EXTR_PIP_PKG
            tests:
              - not_null
          - name: NJ_RESDNC_RLTNSHP_PIP_IND
            tests:
              - not_null
          - name: NY_SSL_IND
            tests:
              - not_null
          - name: NY_FULL_CVG_GLASS_COMP_IND
            tests:
              - not_null
          - name: GRGNG_ZIP
            tests:
              - not_null
          - name: GRGNG_ZIP_5
            tests:
              - not_null
          - name: RATNG_CMPY_CD
            tests:
              - not_null
          - name: MLT_CAR_IND
            tests:
              - not_null
          - name: RT_CLS
            tests:
              - not_null
          - name: AGE
            tests:
              - not_null
          - name: GENDR
            tests:
              - not_null
          - name: MRTL_STAT
            tests:
              - not_null
          - name: AUTO_USE_CD
            tests:
              - not_null
          - name: MILES_TO_WRK
            tests:
              - not_null
          - name: GOOD_STDNT_IND
            tests:
              - not_null
          - name: DRVR_TRNG_IND
            tests:
              - not_null
          - name: SOI_TYP
            tests:
              - not_null
          - name: PHY_DMG_IND
            tests:
              - not_null
          - name: EXPS_VAL_ROLLED
            tests:
              - not_null
          - name: NJ_RATD_PNTS
            tests:
              - not_null
          - name: VEH_MDL_YR
            tests:
              - not_null
          - name: NJ_EXCPTION_CD
            tests:
              - not_null
          - name: NJ_FGVN_PNTS
            tests:
              - not_null
          - name: PASSV_RESTRA_DISC
            tests:
              - not_null
          - name: SNR_DRVR_IND
            tests:
              - not_null
          - name: DEFNS_DRVR_DISC_IND
            tests:
              - not_null
          - name: ANTI_THFT_DISC
            tests:
              - not_null
          - name: DAY_TM_RUN_LIGHTS
            tests:
              - not_null
          - name: LMT_TORT
            tests:
              - not_null
          - name: CVG_TYP_IND
            tests:
              - not_null
          - name: CVG_EXPS_VAL
            tests:
              - not_null
          - name: WRITTN_PREM_AMT
            tests:
              - not_null