{{ config(materialized='table') }}
SELECT
    NISS_APRM_DETL_SK,
    ST_ABBR,
    ST_CD,
    RATNG_CMPY_CD,
    MLT_CAR_IND,
    RT_CLS,
    FINAL_RDRVR_AGE,
    GENDR,
    MRTL_STAT,
    AUTO_USE_CD,
    MILES_TO_WRK,
    GOOD_STDNT_IND,
    DRVR_TRNG_IND,
    SOI_TYP,
    ACCTNG_LOB,
    CVG_TYP_CD,
    CASE when ST_ABBR='FL' and FINAL_RDRVR_AGE!=' ' then 
        case 
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='N' AND (RIGHT(RT_CLS,1)='5' OR RT_CLS IN ('5M','9','5F','2F','2M')) AND MRTL_STAT='M' AND AUTO_USE_CD!='FRM' then '1620'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='N' AND (RIGHT(RT_CLS,1)='5' OR RT_CLS IN ('5M','9','5F','2F','2M')) AND MRTL_STAT='M' AND AUTO_USE_CD='FRM' then '1623'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='Y' AND (RIGHT(RT_CLS,1)='5' OR RT_CLS IN ('5M','9','5F','2F','2M')) AND MRTL_STAT='M' AND AUTO_USE_CD!='FRM' then '1622'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='Y' AND (RIGHT(RT_CLS,1)='5' OR RT_CLS IN ('5M','9','5F','2F','2M')) AND MRTL_STAT='M' AND AUTO_USE_CD='FRM' then '1621'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='N' AND (RIGHT(RT_CLS,1)='2' OR RT_CLS IN ('2M','9','5M','2F')) AND MRTL_STAT='S' AND AUTO_USE_CD!='FRM' then '1630'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='N' AND (RIGHT(RT_CLS,1)='2' OR RT_CLS IN ('2M','9','2F')) AND MRTL_STAT='S' AND AUTO_USE_CD='FRM' then '1633'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='Y' AND (RIGHT(RT_CLS,1)='2' OR RT_CLS IN ('2M','9','2F','5M')) AND (MRTL_STAT IN ('S','') OR MRTL_STAT IS NULL) AND AUTO_USE_CD!='FRM' then '1632'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='Y' AND (RIGHT(RT_CLS,1)='2' OR RT_CLS IN ('2M','9','2F','5M')) AND (MRTL_STAT IN ('S','') OR MRTL_STAT IS NULL) AND AUTO_USE_CD='FRM' then '1631'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='N' AND RT_CLS IN ('08','18','28','38','48','58','M6','M8','N6','N8','3','5F','2F','2M','9') AND AUTO_USE_CD!='FRM' then '1610'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='N' AND RT_CLS IN ('08','18','28','38','48','58','M6','M8','N6','N8','3','5F','2F','2M') AND AUTO_USE_CD='FRM' then '1613'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='Y' AND RT_CLS IN ('08','18','28','38','48','58','M6','M8','N6','N8','3','5F','2F','2M') AND AUTO_USE_CD!='FRM' then '1612'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='Y' AND RT_CLS IN ('08','18','28','38','48','58','M6','M8','N6','N8','3','5F','2F','2M') AND AUTO_USE_CD='FRM' then '1611'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='N'  AND GENDR='F' AND AUTO_USE_CD!='FRM' then '1640'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='N'  AND GENDR='F' AND AUTO_USE_CD='FRM' then '1643'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='Y'  AND GENDR='F' AND AUTO_USE_CD!='FRM' then '1642'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<25 AND RATNG_CMPY_CD='K' AND MLT_CAR_IND='Y'  AND GENDR='F' AND AUTO_USE_CD='FRM' then '1641'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>24 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<30 AND MLT_CAR_IND='N' AND (AUTO_USE_CD IN ('HOP','HPS','PLS','STG','COM','#') or AUTO_USE_CD!='FRM') then '1650'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>24 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<30 AND  MLT_CAR_IND='N' AND  AUTO_USE_CD IN ('FRM') then '1653'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>24 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<30 AND MLT_CAR_IND='Y' AND (AUTO_USE_CD IN ('HOP','HPS','PLS','STG','COM','#') or AUTO_USE_CD!='FRM') then '1652'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>24 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<30 AND  MLT_CAR_IND='Y' AND  AUTO_USE_CD IN ('FRM') then '1651'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND  MLT_CAR_IND='N' AND AUTO_USE_CD IN ('FRM') then '1213'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND  MLT_CAR_IND='N' AND AUTO_USE_CD IN ('HOP','HPS','PLS','STG','#') then '1210'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND  MLT_CAR_IND='Y' AND AUTO_USE_CD IN ('HOP','HPS','PLS','STG','#') then '1212'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND  MLT_CAR_IND='Y' AND AUTO_USE_CD IN ('FRM') then '1211'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND  MLT_CAR_IND='N' AND AUTO_USE_CD IN ('COM') AND TO_NUMBER(MILES_TO_WRK, 38, 0)<10 then '1220'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND  MLT_CAR_IND='Y' AND AUTO_USE_CD IN ('COM') AND TO_NUMBER(MILES_TO_WRK, 38, 0)<10 then '1222'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND  MLT_CAR_IND='N' AND AUTO_USE_CD IN ('COM') AND TO_NUMBER(MILES_TO_WRK, 38, 0)>=10 then '1230'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND  MLT_CAR_IND='Y' AND AUTO_USE_CD IN ('COM') AND TO_NUMBER(MILES_TO_WRK, 38, 0)>=10 then '1232'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND  MLT_CAR_IND='N' AND AUTO_USE_CD NOT IN ('HOP','HPS','PLS','STG','#','FRM','COM') then '1400'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>29 AND TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)<65 AND  MLT_CAR_IND='Y' AND AUTO_USE_CD NOT IN ('HOP','HPS','PLS','STG','#','FRM','COM') then '1402'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND  MLT_CAR_IND='N' AND AUTO_USE_CD  IN ('PLS','STG','#') then '1510'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND  MLT_CAR_IND='N' AND AUTO_USE_CD IN ('COM') AND TO_NUMBER(MILES_TO_WRK, 38, 0)<10 then '1520'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND  MLT_CAR_IND='N' AND AUTO_USE_CD IN ('COM') AND TO_NUMBER(MILES_TO_WRK, 38, 0)>=10 then '1530'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND  MLT_CAR_IND='N' AND AUTO_USE_CD IN ('FRM')  then '1513'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND  MLT_CAR_IND='N' AND AUTO_USE_CD NOT IN ('PLS','STG','FRM','COM','#')  then '1550'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND  MLT_CAR_IND='Y' AND AUTO_USE_CD  IN ('PLS','STG','#') then '1512'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND  MLT_CAR_IND='Y' AND AUTO_USE_CD IN ('COM') AND TO_NUMBER(MILES_TO_WRK, 38, 0)<10 then '1522'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND  MLT_CAR_IND='Y' AND AUTO_USE_CD IN ('COM') AND TO_NUMBER(MILES_TO_WRK, 38, 0)>=10 then '1532'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND  MLT_CAR_IND='Y' AND AUTO_USE_CD IN ('FRM') then '1511'
            when TO_NUMBER(FINAL_RDRVR_AGE, 38, 0)>64 AND  MLT_CAR_IND='Y' AND AUTO_USE_CD NOT IN ('PLS','STG','FRM','COM','#')  then '1552'
        end 
    else '' 
    end as NISS_CLASS_CD_FL,
    REC_EXCPN_IND,
    REC_EXCPN_RSN_DESC
FROM (
    SELECT
        NISS_APRM_DETL_SK,
        LTRIM(RTRIM(ST_ABBR)) ST_ABBR,
        LTRIM(RTRIM(ST_CD)) ST_CD,
        LTRIM(RTRIM(RATNG_CMPY_CD)) RATNG_CMPY_CD,
        LTRIM(RTRIM(MLT_CAR_IND)) MLT_CAR_IND,
        LTRIM(RTRIM(RT_CLS)) RT_CLS,
        LTRIM(RTRIM( FINAL_RDRVR_AGE)) FINAL_RDRVR_AGE,
        LTRIM(RTRIM(GENDR)) GENDR,
        LTRIM(RTRIM(MRTL_STAT)) MRTL_STAT,
        LTRIM(RTRIM(AUTO_USE_CD)) AUTO_USE_CD,
        LTRIM(RTRIM(MILES_TO_WRK)) MILES_TO_WRK,
        LTRIM(RTRIM(GOOD_STDNT_IND)) GOOD_STDNT_IND,
        LTRIM(RTRIM(DRVR_TRNG_IND)) DRVR_TRNG_IND,
        LTRIM(RTRIM(SOI_TYP)) SOI_TYP,
        LTRIM(RTRIM(ACCTNG_LOB)) ACCTNG_LOB,
        LTRIM(RTRIM(CVG_TYP_CD)) CVG_TYP_CD,
        REC_EXCPN_IND,
        REC_EXCPN_RSN_DESC
    FROM {{ source('FDR', 'WRK_BIRP_NISS_APRM_DETL') }}
    WHERE ST_ABBR NOT IN ('NY','NJ') AND SOURCE_IND_DERIVED='FARMERS'
)
```

This code block contains the DBT models converted from the Informatica PowerCenter source definitions with SQL Override or Lookup SQL Override. Each model is defined with a `config` block for materialization and uses DBT functions like `{{ source() }}` and `{{ var() }}` to reference sources and variables. The SQL logic from the overrides is preserved, including transformations and filters.