-- Purpose: Transform and split BI limit and coverage amount fields for further processing.

WITH transformed_data AS (
    SELECT
        BI_LMT,
        REPLACE(BI_LMT, ',', '') AS v_BI_LMT,
        LENGTH(REPLACE(BI_LMT, ',', '')) AS v_BI_LMT_Parts,
        POSITION('/' IN BI_LMT) AS v_BI_LMT_Part1_Pos,
        POSITION('/' IN BI_LMT, POSITION('/' IN BI_LMT) + 1) AS v_BI_LMT_Part2_Pos,
        SUBSTRING(BI_LMT, 1, POSITION('/' IN BI_LMT) - 1) AS v_Limit_FIELD1,
        SUBSTRING(BI_LMT, POSITION('/' IN BI_LMT) + 1, POSITION('/' IN BI_LMT, POSITION('/' IN BI_LMT) + 1) - POSITION('/' IN BI_LMT) - 1) AS v_Limit_FIELD2,
        SUBSTRING(BI_LMT, POSITION('/' IN BI_LMT, POSITION('/' IN BI_LMT) + 1) + 1) AS v_Limit_FIELD3,
        CAST(SUBSTRING(BI_LMT, 1, POSITION('/' IN BI_LMT) - 1) AS INTEGER) AS BI_LMT_1_Decimal,
        CAST(SUBSTRING(BI_LMT, POSITION('/' IN BI_LMT) + 1, POSITION('/' IN BI_LMT, POSITION('/' IN BI_LMT) + 1) - POSITION('/' IN BI_LMT) - 1) AS INTEGER) AS BI_LMT_2_Decimal,
        CAST(SUBSTRING(BI_LMT, POSITION('/' IN BI_LMT, POSITION('/' IN BI_LMT) + 1) + 1) AS INTEGER) AS BI_LMT_3_Decimal,
        LENGTH(REPLACE(BI_LMT, '/', '')) AS BI_LMT_NO_OF_PARTS,
        BI_LMT AS SRC_BI_LMT,
        REC_EXCPN_IND,
        REC_EXCPN_RSN_DESC,
        CVG_AMT,
        REPLACE(CVG_AMT, ',', '') AS v_CVG_AMT,
        LENGTH(REPLACE(CVG_AMT, ',', '')) AS v_CVG_AMT_Parts,
        POSITION('/' IN CVG_AMT) AS v_CVG_AMT_Part1_Pos,
        POSITION('/' IN CVG_AMT, POSITION('/' IN CVG_AMT) + 1) AS v_CVG_AMT_Part2_Pos,
        SUBSTRING(CVG_AMT, 1, POSITION('/' IN CVG_AMT) - 1) AS v_AMOUNT_FIELD1,
        SUBSTRING(CVG_AMT, POSITION('/' IN CVG_AMT) + 1, POSITION('/' IN CVG_AMT, POSITION('/' IN CVG_AMT) + 1) - POSITION('/' IN CVG_AMT) - 1) AS v_AMOUNT_FIELD2,
        SUBSTRING(CVG_AMT, POSITION('/' IN CVG_AMT, POSITION('/' IN CVG_AMT) + 1) + 1) AS v_AMOUNT_FIELD3,
        SUBSTRING(CVG_AMT, 1, POSITION('/' IN CVG_AMT) - 1) AS CVG_AMT_1_String,
        SUBSTRING(CVG_AMT, POSITION('/' IN CVG_AMT) + 1, POSITION('/' IN CVG_AMT, POSITION('/' IN CVG_AMT) + 1) - POSITION('/' IN CVG_AMT) - 1) AS CVG_AMT_2_String,
        SUBSTRING(CVG_AMT, POSITION('/' IN CVG_AMT, POSITION('/' IN CVG_AMT) + 1) + 1) AS CVG_AMT_3_String,
        CAST(SUBSTRING(CVG_AMT, 1, POSITION('/' IN CVG_AMT) - 1) AS DECIMAL) AS CVG_AMT_1_Decimal,
        CAST(SUBSTRING(CVG_AMT, POSITION('/' IN CVG_AMT) + 1, POSITION('/' IN CVG_AMT, POSITION('/' IN CVG_AMT) + 1) - POSITION('/' IN CVG_AMT) - 1) AS DECIMAL) AS CVG_AMT_2_Decimal,
        CAST(SUBSTRING(CVG_AMT, POSITION('/' IN CVG_AMT, POSITION('/' IN CVG_AMT) + 1) + 1) AS DECIMAL) AS CVG_AMT_3_Decimal,
        LENGTH(REPLACE(CVG_AMT, '/', '')) AS CVG_AMT_NO_OF_PARTS,
        CVG_AMT AS SRC_CVG_AMT
    FROM {{ source('power_center', 'WRK_BIRP_TA_NISS_NU0C_APRM_DTL') }}
)

SELECT * FROM transformed_data