-- Purpose: Intermediate transformation for NISS auto parameters
WITH base_data AS (
    SELECT
        PRINCIPAL_OPRT,
        SOURCE_IND_DERIVED,
        NISS_CMPNY_CD,
        REG_PER_YR,
        FISC_PER_YR,
        NAIC_CMPNY_CD,
        ST_NM,
        ST_CD,
        ACCTNG_LOB,
        SUBSTR(LTRIM(RTRIM(ACCTNG_LOB)), 1, 3) AS o_ANNUAL_STMT_LOB,
        CVG_TYP_CD,
        CVG_AMT,
        BI_LMT,
        GA_ADDED_AT_FAULT_IND AS i_GA_ADDED_AT_FAULT_IND,
        GA_ADDED_AT_FAULT_IND,
        PLCY_IND,
        UM_UMI_STACKING,
        PIP_WVR_WL_IND,
        PIP_MED_SEC_IND,
        PIP_LOSS_INCOME_IND,
        MI_PPO_IND,
        PRD_GRP_CD,
        NJ_HLTH_INSR_PRIM,
        NJ_EXTR_PIP_PKG,
        NJ_RESDNC_RLTNSHP_PIP_IND,
        NY_SSL_IND,
        NY_FULL_CVG_GLASS_COMP_IND,
        GRGNG_ZIP AS i_GRGNG_ZIP,
        GRGNG_ZIP_5,
        RATNG_CMPY_CD,
        MLT_CAR_IND,
        RT_CLS,
        AGE,
        GENDR,
        MRTL_STAT,
        AUTO_USE_CD,
        MILES_TO_WRK,
        GOOD_STDNT_IND,
        DRVR_TRNG_IND,
        SOI_TYP,
        PHY_DMG_IND,
        EXPS_VAL_ROLLED,
        NJ_RATD_PNTS,
        VEH_MDL_YR,
        NJ_EXCPTION_CD,
        NJ_FGVN_PNTS,
        PASSV_RESTRA_DISC,
        SNR_DRVR_IND,
        DEFNS_DRVR_DISC_IND,
        ANTI_THFT_DISC,
        DAY_TM_RUN_LIGHTS,
        LMT_TORT,
        CVG_TYP_IND,
        CVG_EXPS_VAL,
        WRITTN_PREM_AMT
    FROM {{ source('power_center', 'WRK_BIRP_TA_NISS_NU0C_APRM_LND') }}
)

SELECT
    {{ generate_sequence() }} AS row_id,
    base_data.*
FROM base_data