{{ config(materialized='table') }}
SELECT * FROM (
    SELECT 
        REG_PER_YR, 
        FISC_PER_YR, 
        NAIC_CMPY_CD, 
        LTRIM(RTRIM(ST_NM)) AS ST_NM, 
        LTRIM(RTRIM(ST_CD)) AS ST_CD, 
        LTRIM(RTRIM(ACCTNG_LOB)) AS ACCTNG_LOB, 
        CVG_TYP_CD, 
        CVG_AMT, 
        BI_LMT, 
        GA_UMBI_PD_ADDED_IND, 
        FA2_PLCY_IND, 
        UM_UIM_STACKING, 
        PIP_WVR_WL_IND, 
        PIP_MED_SEC_IND, 
        PIP_LOSS_INCOME_IND, 
        MI_PPO_IND, 
        PRD_GRP_CD, 
        NJ_HLTH_INSR_PRIM, 
        NJ_EXTR_PIP_PKG, 
        NJ_RESDNC_RLTNSHP_PIP_IND, 
        NY_SSL_IND, 
        NY_FULL_CVG_GLASS_COMP_IND, 
        NJ_NO_LWST_LMT_IND, 
        NJ_NMD_DRVR_EXCL_IND, 
        GRGNG_ZIP_5, 
        RATNG_CMPY_CD, 
        MLT_CAR_IND, 
        RT_CLS, 
        AGE, 
        GENDR, 
        MRTL_STAT, 
        AUTO_USE_CD, 
        MILES_TO_WRK, 
        GOOD_STDNT_IND, 
        DRVR_TRNG_IND, 
        SOI_TYP, 
        PHY_DMG_IND, 
        NJ_RTD_PNTS, 
        VEH_MDL_YR, 
        NJ_EXCPTION_CD, 
        NJ_FRGVN_PNTS, 
        PASSV_RESTRA_DISC, 
        SNR_DRVR_IND, 
        DEFNS_DRVR_DISC_IND, 
        ANTI_THFT_DISC, 
        DAY_TM_RUN_LIGHTS, 
        LMT_TORT, 
        CVG_TYP_IND, 
        CVG_EXPS_VAL, 
        TTL_WRITTN_PREM_AMT, 
        COMP_DED, 
        COLL_DED, 
        LTRIM(RTRIM(PLCY_CNTRCT_NUM)) AS PLCY_CNTRCT_NUM, 
        UNIT_NUM, 
        EFF_DT, 
        NUM_OF_CARS_IN_HH, 
        RDRVR_DT_OF_BRTH, 
        TERM_STRT_DT, 
        COALESCE(SRC_SYS_CD,'') as SRC_SYS_CD, 
        PNI_AGE
    FROM (
        SELECT 
            REGPER.CLNDR_YR REG_PER_YR, 
            FISCPER.CLNDR_YR FISC_PER_YR, 
            PLCY.PLCY_CNTRCT_NUM, 
            MPLCY.BI_LMT, 
            MPLCY.FA2_PLCY_IND, 
            MPLCY.RATNG_CMPY_CD, 
            EPLCY.NAIC_CMPY_CD, 
            EPLCY.PHY_DMG_IND, 
            EPLCY.NY_SSL_IND, 
            EPLCY.GA_UMBI_PD_ADDED_IND, 
            SOI.DRVR_TRNG_IND, 
            SOI.SOI_TYP, 
            SOI.VEH_MDL_YR, 
            SOI.SNR_DRVR_IND, 
            SOI.UNIT_NUM, 
            ESOI.UM_UIM_STACKING, 
            ESOI.PIP_WVR_WL_IND, 
            ESOI.PIP_MED_SEC_IND, 
            ESOI.PIP_LOSS_INCOME_IND, 
            ESOI.MI_PPO_IND, 
            ESOI.PRD_GRP_CD, 
            ESOI.NJ_HLTH_INSR_PRIM, 
            ESOI.NJ_EXTR_PIP_PKG, 
            ESOI.NJ_RESDNC_RLTNSHP_PIP_IND, 
            ESOI.NY_FULL_CVG_GLASS_COMP_IND, 
            ESOI.NJ_NO_LWST_LMT_IND, 
            ESOI.NJ_NMD_DRVR_EXCL_IND, 
            ESOI.RT_CLS, 
            ESOI.AGE, 
            ESOI.GENDR, 
            ESOI.MRTL_STAT, 
            ESOI.AUTO_USE_CD, 
            ESOI.MILES_TO_WRK, 
            ESOI.NJ_EXCPTION_CD, 
            ESOI.PASSV_RESTRA_DISC, 
            ESOI.DEFNS_DRVR_DISC_IND, 
            ESOI.ANTI_THFT_DISC, 
            ESOI.DAY_TM_RUN_LIGHTS, 
            ESOI.LMT_TORT, 
            ESOI.COMP_DED, 
            MSOI.MLT_CAR_IND, 
            MSOI.GOOD_STDNT_IND, 
            MSOI.COLL_DED, 
            CVG.ACCTNG_LOB, 
            CVG.CVG_TYP_CD, 
            ECVG.EFF_DT, 
            ECVG.NJ_RTD_PNTS, 
            ECVG.NJ_FRGVN_PNTS, 
            ECVG.CVG_TYP_IND, 
            MCVG.CVG_AMT, 
            GEOS.ST_NM, 
            GEOS.ST_CD, 
            RGEO.GRGNG_ZIP_5, 
            SUM(COALESCE(FACT.TTL_WRITTN_PREM_AMT,0)) TTL_WRITTN_PREM_AMT, 
            SUM(COALESCE(FACT.CVG_EXPS_VAL,0)) CVG_EXPS_VAL, 
            HH.NUM_OF_CARS_IN_HH, 
            ESOI.RDRVR_DT_OF_BRTH, 
            PLCY.TERM_STRT_DT, 
            PLCY.SRC_SYS_CD, 
            PLCY.PNI_AGE
        FROM 
            {{ source('AGDM', 'FACT_AG_WRITTN_PREM_CVG_LVL') }} FACT
            JOIN {{ source('AGDM', 'DIM_AG_PLCY') }} PLCY ON FACT.PLCY_SK=PLCY.PLCY_SK
            JOIN {{ source('AGDM', 'DIM_AG_MINI_PLCY') }} MPLCY ON FACT.MINI_PLCY_SK = MPLCY.MINI_PLCY_SK
            JOIN {{ source('AGDM', 'DIM_AG_PLCY_ENH') }} EPLCY ON FACT.PLCY_ENH_SK = EPLCY.PLCY_ENH_SK
            JOIN {{ source('AGDM', 'DIM_AG_TRANS_TYP_PLCY') }} ON FACT.TRANS_TYP_PLCY_SK=AGDM.DIM_AG_TRANS_TYP_PLCY.TRANS_TYP_PLCY_SK
            JOIN {{ source('AGDM', 'DIM_AG_SOI') }} SOI ON FACT.SOI_SK = SOI.SOI_SK
            JOIN {{ source('AGDM', 'DIM_AG_MINI_SOI') }} MSOI ON FACT.MINI_SOI_SK = MSOI.MINI_SOI_SK
            JOIN {{ source('AGDM', 'DIM_AG_SOI_ENH') }} ESOI ON FACT.SOI_ENH_SK = ESOI.SOI_ENH_SK
            JOIN {{ source('AGDM', 'DIM_AG_CVG') }} CVG ON FACT.CVG_SK = CVG.CVG_SK
            JOIN {{ source('AGDM', 'DIM_AG_MINI_CVG') }} MCVG ON FACT.MINI_CVG_SK = MCVG.MINI_CVG_SK
            JOIN {{ source('AGDM', 'DIM_AG_CVG_ENH') }} ECVG ON FACT.ON_OFF_PREM_SK = ECVG.ON_OFF_PREM_SK
            JOIN {{ source('AGDM', 'DIM_AG_FARMR_GEO_DISTR') }} GEOD ON FACT.FARMR_GEO_DISTR_SK = GEOD.FARMR_GEO_DISTR_SK
            JOIN {{ source('AGDM', 'DIM_AG_FARMR_GEO_ST') }} GEOS ON GEOD.FARMR_GEO_ST_SK = GEOS.FARMR_GEO_ST_SK
            JOIN {{ source('AGDM', 'DIM_AG_RATED_GEO') }} RGEO ON FACT.RATED_GEO_SK = RGEO.RATED_GEO_SK
            JOIN {{ source('AGDM', 'DIM_DT') }} REGPER ON FACT.REGSTR_PER_SK=REGPER.DT_SK
            JOIN {{ source('AGDM', 'DIM_DT') }} FISCPER ON FACT.FISC_PER_SK =FISCPER.DT_SK
            JOIN {{ source('AGDM', 'DIM_AG_HH') }} HH ON HH.HH_SK=FACT.HH_SK
        WHERE 
            1 = 1 
            AND TRIM(GEOS.ST_NM) NOT IN ({{ var('GEO_ST_NM') }})
            AND (CASE WHEN {{ var('RUN_TYPE') }} = 'Register' THEN REGPER.CLNDR_YR ELSE FISCPER.CLNDR_YR END) = {{ var('RPT_YEAR') }}
            AND AGDM.DIM_AG_TRANS_TYP_PLCY.TRANS_TYP_PLCY_CD NOT IN ('WO')
            AND (TTL_WRITTN_PREM_AMT !=0 AND CVG_EXPS_VAL!=0)
        GROUP BY 
            REGPER.CLNDR_YR, FISCPER.CLNDR_YR, PLCY.PLCY_CNTRCT_NUM, MPLCY.BI_LMT, MPLCY.FA2_PLCY_IND, MPLCY.RATNG_CMPY_CD, EPLCY.NAIC_CMPY_CD, EPLCY.PHY_DMG_IND, EPLCY.NY_SSL_IND, EPLCY.GA_UMBI_PD_ADDED_IND, SOI.DRVR_TRNG_IND, SOI.SOI_TYP, SOI.VEH_MDL_YR, SOI.SNR_DRVR_IND, SOI.UNIT_NUM, ESOI.UM_UIM_STACKING, ESOI.PIP_WVR_WL_IND, ESOI.PIP_MED_SEC_IND, ESOI.PIP_LOSS_INCOME_IND, ESOI.MI_PPO_IND, ESOI.PRD_GRP_CD, ESOI.NJ_HLTH_INSR_PRIM, ESOI.NJ_EXTR_PIP_PKG, ESOI.NJ_RESDNC_RLTNSHP_PIP_IND, ESOI.NY_FULL_CVG_GLASS_COMP_IND, ESOI.NJ_NO_LWST_LMT_IND, ESOI.NJ_NMD_DRVR_EXCL_IND, ESOI.RT_CLS, ESOI.AGE, ESOI.GENDR, ESOI.MRTL_STAT, ESOI.AUTO_USE_CD, ESOI.MILES_TO_WRK, ESOI.NJ_EXCPTION_CD, ESOI.PASSV_RESTRA_DISC, ESOI.DEFNS_DRVR_DISC_IND, ESOI.ANTI_THFT_DISC, ESOI.DAY_TM_RUN_LIGHTS, ESOI.LMT_TORT, ESOI.COMP_DED, MSOI.MLT_CAR_IND, MSOI.GOOD_STDNT_IND, MSOI.COLL_DED, CVG.ACCTNG_LOB, CVG.CVG_TYP_CD, ECVG.EFF_DT, ECVG.NJ_RTD_PNTS, ECVG.NJ_FRGVN_PNTS, ECVG.CVG_TYP_IND, MCVG.CVG_AMT, GEOS.ST_NM, GEOS.ST_CD, RGEO.GRGNG_ZIP_5, HH.NUM_OF_CARS_IN_HH, ESOI.RDRVR_DT_OF_BRTH, PLCY.TERM_STRT_DT, PLCY.SRC_SYS_CD, PLCY.PNI_AGE
    )
ORDER BY ST_CD, ST_NM
FETCH FIRST 1000 ROWS ONLY