{{
  config(
    materialized='ephemeral'
  )
}}

WITH source_wrk_birp_niss_aprm_detl AS (
  SELECT
    NISS_APRM_DETL_SK,
    CLNDR_YR,
    CALL_YR,
    NAIC_CMPNY_CD,
    NISS_CMPNY_CD,
    ST_NM,
    ST_CD,
    NISS_ST_CD,
    ST_ABBR,
    ACCTNG_LOB,
    CVG_TYP_CD,
    CVG_AMT,
    BI_LMT,
    GA_ADDED_AT_FAULT_IND,
    FA2_PLCY_IND,
    UM_UMI_STACKING,
    PIP_WVR_WL_IND,
    PIP_MED_SEC_IND,
    PIP_LOSS_INCOME_IND,
    MI_PPO_IND,
    PRD_GRP_CD,
    NJ_HLTH_INSR_PRIM,
    NJ_EXTR_PIP_PKG,
    NJ_RESDNC_RLTNSHP_PIP_IND,
    NY_SSL_IND,
    NY_FULL_CVG_GLASS_COMP_IND,
    GRGNG_ZIP_5,
    NISS_TERR_CD,
    RATNG_CMPY_CD,
    MLT_CAR_IND,
    RT_CLS,
    AGE,
    GENDR,
    MRTL_STAT,
    AUTO_USE_CD,
    MILES_TO_WRK,
    GOOD_STDNT_IND,
    DRVR_TRNG_IND,
    SOI_TYP,
    PHY_DMG_IND,
    NJ_RATD_PNTS,
    VEH_MDL_YR,
    NJ_EXCPTION_CD,
    NJ_FGVN_PNTS,
    PASSV_RESTRA_DISC,
    SNR_DRVR_IND,
    DEFNS_DRVR_DISC_IND,
    ANTI_THFT_DISC,
    DAY_TM_RUN_LIGHTS,
    LMT_TORT,
    ANNL_STMNT_LOB_CD,
    CVG_TYP_IND,
    CVG_EXPS_VAL,
    TTL_WRITTN_PREM_AMT,
    LINE_CD,
    ACCDNT_YR,
    NISS_CVG_CD,
    RTNG_ZNE_CD,
    TERM_ZNE_CD,
    NISS_CLASS_CD,
    NISS_ELIG_PNTS_CD,
    NISS_AGE_GRP_CD,
    NISS_CMMCL_IND_CD,
    NISS_EXCPN_CD,
    NISS_FGVNS_CD,
    NISS_PASSV_RESTRA_CD,
    NISS_DEFNS_DRVR_CRD_CD,
    NISS_ANTI_THFT_DVC_CD,
    NISS_DAY_TM_RUN_LAMPS_DISC_CD,
    NISS_PLCY_LMT_CD,
    NISS_DEDUC_CD,
    NISS_SSL_LIAB_CD,
    NISS_SUBLOB_CD,
    NISS_TYP_LOSS_CD,
    NISS_LIAB_OR_NO_FAULT_CD,
    NISS_ANNL_STMNT_LOB_CD,
    NISS_PD_LOSS,
    NISS_PD_ALLOC_ADJUS_EXPNS,
    NISS_OUTSTNDG_LOSS,
    NISS_NO_PD_CLMS,
    NISS_NO_OUTSTND_CLMS,
    RSVD_NISS_USE,
    NISS_RSVD_CMPNY_USE,
    NISS_MNFCTRS_MDL_YR,
    CR_BY_MAPNG_ID,
    DW_CR_TMSP,
    UPD_BY_MAPNG_ID,
    DW_UPD_TMSP,
    WRK_FLOW_RUN_ID,
    NJ_NO_LWST_LMT_IND,
    NJ_NMD_DRVR_EXCL_IND,
    EXPS_VAL_ROLLED,
    CVG_CNT_IND,
    CVG_CNT,
    CVG_CD_SK,
    CVG_ATTR_SK,
    REC_DROP_IND,
    REC_DROP_RSN_DESC,
    REC_EXCPN_IND,
    REC_EXCPN_RSN_DESC,
    CVG_ATTR_CHCKSUM,
    COMP_DED,
    COLL_DED,
    PLCY_CNTRCT_NUM,
    UNIT_NUM,
    EFF_DT,
    NUM_OF_CARS_IN_HH,
    RDRVR_DT_OF_BRTH,
    TERM_STRT_DT,
    SRC_SYS_CD,
    DERIVED_RDRVR_AGE,
    FINAL_RDRVR_AGE,
    PNI_AGE,
    LOB,
    PRINCIPAL_OPRT,
    SOURCE_IND_DERIVED
  FROM {{ source('GENAI_POWER_BI', 'WRK_BIRP_NISS_APRM_DETL') }}
),

source_fdr_lib_wrk_birp_niss_aprm_detl AS (
  SELECT DISTINCT
    Y.CVG_CD_ATTR_SK
  FROM (
    SELECT DISTINCT
      CVG_TYP_CD,
      CVG_TYP_IND,
      CVG_CD_ATTR,
      ROW_NUMBER() OVER (ORDER BY CVG_CD_ATTR) AS CVG_CD_ATTR_SK
    FROM (
      SELECT DISTINCT
        CVG_TYP_CD,
        CVG_TYP_IND,
        CONCAT(
          CLNDR_YR, NISS_CMPNY_CD, NISS_ST_CD, GRGNG_ZIP_5, NISS_TERR_CD, LINE_CD, ACCDNT_YR, NISS_CVG_CD,
          RTNG_ZNE_CD, TERM_ZNE_CD, NISS_CLASS_CD, NISS_ELIG_PNTS_CD, NISS_AGE_GRP_CD, NISS_CMMCL_IND_CD, NISS_EXCPN_CD,
          NISS_FGVNS_CD, NISS_PASSV_RESTRA_CD, NISS_DEFNS_DRVR_CRD_CD, NISS_ANTI_THFT_DVC_CD, NISS_DAY_TM_RUN_LAMPS_DISC_CD,
          NISS_PLCY_LMT_CD, NISS_DEDUC_CD, NISS_SSL_LIAB_CD, NISS_SUBLOB_CD, NISS_TYP_LOSS_CD, NISS_LIAB_OR_NO_FAULT_CD,
          NISS_ANNL_STMNT_LOB_CD, NISS_PD_LOSS, NISS_PD_ALLOC_ADJUS_EXPNS, NISS_OUTSTNDG_LOSS, NISS_NO_PD_CLMS,
          NISS_NO_OUTSTND_CLMS, RSVD_NISS_USE, NISS_RSVD_CMPNY_USE, NISS_MNFCTRS_MDL_YR, CVG_TYP_CD, CVG_TYP_IND
        ) AS CVG_CD_ATTR
      FROM (
        SELECT DISTINCT
          TRIM(CLNDR_YR) AS CLNDR_YR,
          TRIM(NISS_CMPNY_CD) AS NISS_CMPNY_CD,
          TRIM(NISS_ST_CD) AS NISS_ST_CD,
          TRIM(GRGNG_ZIP_5) AS GRGNG_ZIP_5,
          TRIM(NISS_TERR_CD) AS NISS_TERR_CD,
          TRIM(CVG_TYP_CD) AS CVG_TYP_CD,
          TRIM(CVG_TYP_IND) AS CVG_TYP_IND,
          TRIM(LINE_CD) AS LINE_CD,
          TRIM(ACCDNT_YR) AS ACCDNT_YR,
          TRIM(NISS_CVG_CD) AS NISS_CVG_CD,
          TRIM(RTNG_ZNE_CD) AS RTNG_ZNE_CD,
          TRIM(TERM_ZNE_CD) AS TERM_ZNE_CD,
          TRIM(NISS_CLASS_CD) AS NISS_CLASS_CD,
          TRIM(NISS_ELIG_PNTS_CD) AS NISS_ELIG_PNTS_CD,
          CAST(NISS_AGE_GRP_CD AS STRING) AS NISS_AGE_GRP_CD,
          TRIM(NISS_CMMCL_IND_CD) AS NISS_CMMCL_IND_CD,
          TRIM(NISS_EXCPN_CD) AS NISS_EXCPN_CD,
          TRIM(NISS_FGVNS_CD) AS NISS_FGVNS_CD,
          TRIM(NISS_PASSV_RESTRA_CD) AS NISS_PASSV_RESTRA_CD,
          TRIM(NISS_DEFNS_DRVR_CRD_CD) AS NISS_DEFNS_DRVR_CRD_CD,
          TRIM(NISS_ANTI_THFT_DVC_CD) AS NISS_ANTI_THFT_DVC_CD,
          TRIM(NISS_DAY_TM_RUN_LAMPS_DISC_CD) AS NISS_DAY_TM_RUN_LAMPS_DISC_CD,
          TRIM(NISS_PLCY_LMT_CD) AS NISS_PLCY_LMT_CD,
          TRIM(NISS_DEDUC_CD) AS NISS_DEDUC_CD,
          TRIM(NISS_SSL_LIAB_CD) AS NISS_SSL_LIAB_CD,
          TRIM(NISS_SUBLOB_CD) AS NISS_SUBLOB_CD,
          TRIM(NISS_TYP_LOSS_CD) AS NISS_TYP_LOSS_CD,
          TRIM(NISS_LIAB_OR_NO_FAULT_CD) AS NISS_LIAB_OR_NO_FAULT_CD,
          TRIM(NISS_ANNL_STMNT_LOB_CD) AS NISS_ANNL_STMNT_LOB_CD,
          COALESCE(NISS_PD_LOSS, 0) AS NISS_PD_LOSS,
          COALESCE(NISS_PD_ALLOC_ADJUS_EXPNS, 0) AS NISS_PD_ALLOC_ADJUS_EXPNS,
          COALESCE(NISS_OUTSTNDG_LOSS, 0) AS NISS_OUTSTNDG_LOSS,
          COALESCE(NISS_NO_PD_CLMS, 0) AS NISS_NO_PD_CLMS,
          COALESCE(NISS_NO_OUTSTND_CLMS, 0) AS NISS_NO_OUTSTND_CLMS,
          COALESCE(TRIM(RSVD_NISS_USE), '0') AS RSVD_NISS_USE,
          TRIM(NISS_RSVD_CMPNY_USE) AS NISS_RSVD_CMPNY_USE,
          COALESCE(NISS_MNFCTRS_MDL_YR, 0) AS NISS_MNFCTRS_MDL_YR
        FROM {{ source('GENAI_POWER_BI', 'WRK_BIRP_NISS_APRM_DETL') }}
      )
    )
  ) X
),
exp_to_generate_cvg_cd_sk AS (
  SELECT
    NISS_APRM_DETL_SK,
    CVG_ATTR_SK,
    CVG_CD_ATTR_SK
  FROM source_fdr_lib_wrk_birp_niss_aprm_detl
),
upd_cvg_cd_sk AS (
  SELECT
    NISS_APRM_DETL_SK,
    CVG_CD_ATTR_SK
  FROM exp_to_generate_cvg_cd_sk
)

SELECT *
FROM upd_cvg_cd_sk