{{ config(materialized='view') }}

WITH source_wrk_birp_niss_aprm_final AS (
  SELECT 
    NISS_APRM_FINAL_SK,
    CLNDR_YR,
    CALL_YR,
    NISS_CMPNY_CD,
    ST_NM,
    ST_CD,
    ST_ABBR,
    NISS_ST_CD,
    LINE_CD,
    ACCDNT_YR,
    NISS_CVG_CD,
    NISS_TERR_CD,
    RTNG_ZNE_CD,
    TERM_ZNE_CD,
    GRGNG_ZIP_5,
    NISS_CLASS_CD,
    NISS_ELIG_PNTS_CD,
    NISS_AGE_GRP_CD,
    NISS_CMMCL_IND_CD,
    NISS_EXCPN_CD,
    NISS_FGVNS_CD,
    NISS_PASSV_RESTRA_CD,
    NISS_DEFNS_DRVR_CRD_CD,
    NISS_ANTI_THFT_DVC_CD,
    NISS_DAY_TM_RUN_LAMPS_DISC_CD,
    NISS_PLCY_LMT_CD,
    NISS_DEDUC_CD,
    NISS_SSL_LIAB_CD,
    NISS_SUBLOB_CD,
    NISS_TYP_LOSS_CD,
    NISS_LIAB_OR_NO_FAULT_CD,
    NISS_ANNL_STMNT_LOB_CD,
    CVG_EXPS_VAL,
    TTL_WRITTN_PREM_AMT,
    NISS_PD_LOSS,
    NISS_PD_ALLOC_ADJUS_EXPNS,
    NISS_OUTSTNDG_LOSS,
    NISS_NO_PD_CLMS,
    NISS_NO_OUTSTND_CLMS,
    RSVD_NISS_USE,
    NISS_RSVD_CMPNY_USE,
    NISS_MNFCTRS_MDL_YR,
    CR_BY_MAPNG_ID,
    DW_CR_TMSP,
    UPD_BY_MAPNG_ID,
    DW_UPD_TMSP,
    WRK_FLOW_RUN_ID
  FROM {{ source('GENAI_POWER_BI', 'WRK_BIRP_NISS_APRM_FINAL') }}
),

source_fdr_lib_wrk_birp_niss_aprm_detl AS (
  SELECT 
    COALESCE(DTL.CLNDR_YR, FNL.CLNDR_YR) AS CLNDR_YR,
    COALESCE(DTL.NISS_CMPNY_CD, FNL.NISS_CMPNY_CD) AS NISS_CMPNY_CD,
    COALESCE(DTL.ST_NM, FNL.ST_NM) AS ST_NM,
    COALESCE(DTL_PREM_AMT, 0) AS DET_PREM_AMT,
    COALESCE(DROP_PREM_AMT, 0) AS DROP_PREM_AMT,
    COALESCE(FNL_PREM_AMT, 0) AS FNL_PREM_AMT
  FROM (
    SELECT 
      COALESCE(D_ALL.CLNDR_YR, D_DROP.CLNDR_YR) AS CLNDR_YR,
      COALESCE(D_ALL.NISS_CMPNY_CD, D_DROP.NISS_CMPNY_CD) AS NISS_CMPNY_CD,
      COALESCE(D_ALL.ST_NM, D_DROP.ST_NM) AS ST_NM,
      COALESCE(DTL_PREM_AMT, 0) AS DTL_PREM_AMT,
      COALESCE(DROP_PREM_AMT, 0) AS DROP_PREM_AMT
    FROM (
      SELECT 
        CLNDR_YR, 
        NISS_CMPNY_CD, 
        ST_NM,
        SUM(TTL_WRITTN_PREM_AMT) AS DTL_PREM_AMT
      FROM {{ source('GENAI_POWER_BI', 'WRK_BIRP_NISS_APRM_DETL') }}
      GROUP BY CLNDR_YR, NISS_CMPNY_CD, ST_NM
    ) D_ALL
    FULL OUTER JOIN (
      SELECT 
        CLNDR_YR, 
        NISS_CMPNY_CD, 
        ST_NM,
        SUM(TTL_WRITTN_PREM_AMT) AS DROP_PREM_AMT
      FROM {{ source('GENAI_POWER_BI', 'WRK_BIRP_NISS_APRM_DETL') }}
      WHERE REC_DROP_IND = 'Y'
      GROUP BY CLNDR_YR, NISS_CMPNY_CD, ST_NM
    ) D_DROP
    ON D_ALL.CLNDR_YR = D_DROP.CLNDR_YR
    AND D_ALL.NISS_CMPNY_CD = D_DROP.NISS_CMPNY_CD
    AND D_ALL.ST_NM = D_DROP.ST_NM
  ) DTL
  FULL OUTER JOIN (
    SELECT 
      CLNDR_YR, 
      NISS_CMPNY_CD, 
      ST_NM,
      SUM(TTL_WRITTN_PREM_AMT) AS FNL_PREM_AMT
    FROM {{ source('GENAI_POWER_BI', 'WRK_BIRP_NISS_APRM_FINAL') }}
    GROUP BY CLNDR_YR, NISS_CMPNY_CD, ST_NM
  ) FNL
  ON DTL.CLNDR_YR = FNL.CLNDR_YR
  AND DTL.NISS_CMPNY_CD = FNL.NISS_CMPNY_CD
  AND DTL.ST_NM = FNL.ST_NM
),

exp_derive_balance_indicator AS (
  SELECT 
    CLNDR_YR,
    SUBSTRING(TRIM(CLNDR_YR), 3, 2) AS o_CLNDR_YR,
    NISS_CMPNY_CD,
    ST_NM,
    DET_PREM_AMT,
    DROP_PREM_AMT,
    FNL_PREM_AMT,
    DET_PREM_AMT - DROP_PREM_AMT - FNL_PREM_AMT AS BAL_DIFF,
    CASE 
      WHEN DET_PREM_AMT - DROP_PREM_AMT - FNL_PREM_AMT = 0 THEN 'Y'
      ELSE 'N'
    END AS BAL_IND
  FROM source_fdr_lib_wrk_birp_niss_aprm_detl
)

SELECT * 
FROM exp_derive_balance_indicator