{{
  config(
    materialized='view'
  )
}}

WITH source_data AS (
  SELECT
    NISS_APRM_DETL_SK,
    -- Apply transformations to clean and format fields
    CASE WHEN TRIM(CLNDR_YR) IS NULL OR TRIM(CLNDR_YR) = '' THEN ' ' ELSE TRIM(CLNDR_YR) END AS CLNDR_YR,
    CASE WHEN TRIM(CALL_YR) IS NULL OR TRIM(CALL_YR) = '' THEN ' ' ELSE TRIM(CALL_YR) END AS CALL_YR,
    CASE WHEN TRIM(NISS_CMPNY_CD) IS NULL OR TRIM(NISS_CMPNY_CD) = '' THEN ' ' ELSE TRIM(NISS_CMPNY_CD) END AS NISS_CMPNY_CD,
    CASE WHEN TRIM(NISS_ST_CD) IS NULL OR TRIM(NISS_ST_CD) = '' THEN ' ' ELSE TRIM(NISS_ST_CD) END AS NISS_ST_CD,
    CASE WHEN TRIM(GRGNG_ZIP_5) IS NULL OR TRIM(GRGNG_ZIP_5) = '' THEN ' ' ELSE TRIM(GRGNG_ZIP_5) END AS GRGNG_ZIP_5,
    CASE WHEN TRIM(NISS_TERR_CD) IS NULL OR TRIM(NISS_TERR_CD) = '' THEN ' ' ELSE TRIM(NISS_TERR_CD) END AS NISS_TERR_CD,
    CASE WHEN TRIM(LINE_CD) IS NULL OR TRIM(LINE_CD) = '' THEN ' ' ELSE TRIM(LINE_CD) END AS LINE_CD,
    CASE WHEN TRIM(ACCDNT_YR) IS NULL OR TRIM(ACCDNT_YR) = '' THEN ' ' ELSE TRIM(ACCDNT_YR) END AS ACCDNT_YR,
    CASE WHEN TRIM(NISS_CVG_CD) IS NULL OR TRIM(NISS_CVG_CD) = '' THEN ' ' ELSE TRIM(NISS_CVG_CD) END AS NISS_CVG_CD,
    CASE WHEN TRIM(RTNG_ZNE_CD) IS NULL OR TRIM(RTNG_ZNE_CD) = '' THEN ' ' ELSE TRIM(RTNG_ZNE_CD) END AS RTNG_ZNE_CD,
    CASE WHEN TRIM(TERM_ZNE_CD) IS NULL OR TRIM(TERM_ZNE_CD) = '' THEN ' ' ELSE TRIM(TERM_ZNE_CD) END AS TERM_ZNE_CD,
    CASE WHEN TRIM(NISS_CLASS_CD) IS NULL OR TRIM(NISS_CLASS_CD) = '' THEN ' ' ELSE TRIM(NISS_CLASS_CD) END AS NISS_CLASS_CD,
    CASE WHEN TRIM(NISS_ELIG_PNTS_CD) IS NULL OR TRIM(NISS_ELIG_PNTS_CD) = '' THEN ' ' ELSE TRIM(NISS_ELIG_PNTS_CD) END AS NISS_ELIG_PNTS_CD,
    CAST(COALESCE(NISS_AGE_GRP_CD, 0) AS VARCHAR) AS NISS_AGE_GRP_CD,
    CASE WHEN TRIM(NISS_CMMCL_IND_CD) IS NULL OR TRIM(NISS_CMMCL_IND_CD) = '' THEN ' ' ELSE TRIM(NISS_CMMCL_IND_CD) END AS NISS_CMMCL_IND_CD,
    CASE WHEN TRIM(NISS_EXCPN_CD) IS NULL OR TRIM(NISS_EXCPN_CD) = '' THEN ' ' ELSE TRIM(NISS_EXCPN_CD) END AS NISS_EXCPN_CD,
    CASE WHEN TRIM(NISS_FGVNS_CD) IS NULL OR TRIM(NISS_FGVNS_CD) = '' THEN ' ' ELSE TRIM(NISS_FGVNS_CD) END AS NISS_FGVNS_CD,
    CASE WHEN TRIM(NISS_PASSV_RESTRA_CD) IS NULL OR TRIM(NISS_PASSV_RESTRA_CD) = '' THEN ' ' ELSE TRIM(NISS_PASSV_RESTRA_CD) END AS NISS_PASSV_RESTRA_CD,
    CASE WHEN TRIM(NISS_DEFNS_DRVR_CRD_CD) IS NULL OR TRIM(NISS_DEFNS_DRVR_CRD_CD) = '' THEN ' ' ELSE TRIM(NISS_DEFNS_DRVR_CRD_CD) END AS NISS_DEFNS_DRVR_CRD_CD,
    CASE WHEN TRIM(NISS_ANTI_THFT_DVC_CD) IS NULL OR TRIM(NISS_ANTI_THFT_DVC_CD) = '' THEN ' ' ELSE TRIM(NISS_ANTI_THFT_DVC_CD) END AS NISS_ANTI_THFT_DVC_CD,
    CASE WHEN TRIM(NISS_DAY_TM_RUN_LAMPS_DISC_CD) IS NULL OR TRIM(NISS_DAY_TM_RUN_LAMPS_DISC_CD) = '' THEN ' ' ELSE TRIM(NISS_DAY_TM_RUN_LAMPS_DISC_CD) END AS NISS_DAY_TM_RUN_LAMPS_DISC_CD,
    CASE WHEN TRIM(NISS_PLCY_LMT_CD) IS NULL OR TRIM(NISS_PLCY_LMT_CD) = '' THEN ' ' ELSE TRIM(NISS_PLCY_LMT_CD) END AS NISS_PLCY_LMT_CD,
    CASE WHEN TRIM(NISS_DEDUC_CD) IS NULL OR TRIM(NISS_DEDUC_CD) = '' THEN ' ' ELSE TRIM(NISS_DEDUC_CD) END AS NISS_DEDUC_CD,
    CASE WHEN TRIM(NISS_SSL_LIAB_CD) IS NULL OR TRIM(NISS_SSL_LIAB_CD) = '' THEN ' ' ELSE TRIM(NISS_SSL_LIAB_CD) END AS NISS_SSL_LIAB_CD,
    CASE WHEN TRIM(NISS_SUBLOB_CD) IS NULL OR TRIM(NISS_SUBLOB_CD) = '' THEN ' ' ELSE TRIM(NISS_SUBLOB_CD) END AS NISS_SUBLOB_CD,
    CASE WHEN TRIM(NISS_TYP_LOSS_CD) IS NULL OR TRIM(NISS_TYP_LOSS_CD) = '' THEN ' ' ELSE TRIM(NISS_TYP_LOSS_CD) END AS NISS_TYP_LOSS_CD,
    CASE WHEN TRIM(NISS_LIAB_OR_NO_FAULT_CD) IS NULL OR TRIM(NISS_LIAB_OR_NO_FAULT_CD) = '' THEN ' ' ELSE TRIM(NISS_LIAB_OR_NO_FAULT_CD) END AS NISS_LIAB_OR_NO_FAULT_CD,
    CASE WHEN TRIM(NISS_ANNL_STMNT_LOB_CD) IS NULL OR TRIM(NISS_ANNL_STMNT_LOB_CD) = '' THEN ' ' ELSE TRIM(NISS_ANNL_STMNT_LOB_CD) END AS NISS_ANNL_STMNT_LOB_CD,
    CAST(COALESCE(NISS_PD_LOSS, 0) AS VARCHAR) AS NISS_PD_LOSS,
    CAST(COALESCE(NISS_PD_ALLOC_ADJUS_EXPNS, 0) AS VARCHAR) AS NISS_PD_ALLOC_ADJUS_EXPNS,
    CAST(COALESCE(NISS_OUTSTNDG_LOSS, 0) AS VARCHAR) AS NISS_OUTSTNDG_LOSS,
    CAST(COALESCE(NISS_NO_PD_CLMS, 0) AS VARCHAR) AS NISS_NO_PD_CLMS,
    CAST(COALESCE(NISS_NO_OUTSTND_CLMS, 0) AS VARCHAR) AS NISS_NO_OUTSTND_CLMS,
    CASE WHEN TRIM(RSVD_NISS_USE) IS NULL OR TRIM(RSVD_NISS_USE) = '' THEN '0' ELSE TRIM(RSVD_NISS_USE) END AS RSVD_NISS_USE,
    CASE WHEN TRIM(NISS_RSVD_CMPNY_USE) IS NULL OR TRIM(NISS_RSVD_CMPNY_USE) = '' THEN ' ' ELSE TRIM(NISS_RSVD_CMPNY_USE) END AS NISS_RSVD_CMPNY_USE,
    CAST(COALESCE(NISS_MNFCTRS_MDL_YR, 0) AS VARCHAR) AS NISS_MNFCTRS_MDL_YR,
    CASE WHEN TRIM(PLCY_CNTRCT_NUM) IS NULL OR TRIM(PLCY_CNTRCT_NUM) = '' THEN '' ELSE TRIM(PLCY_CNTRCT_NUM) END AS PLCY_CNTRCT_NUM
  FROM {{ source('GENAI_POWER_BI', 'WRK_BIRP_NISS_APRM_DETL') }}
),

EXP_Gen_CvgAttrCheckSum AS (
  SELECT
    NISS_APRM_DETL_SK,
    -- Concatenate fields to generate CVG_ATTR
    CONCAT(
      CLNDR_YR, CALL_YR, NISS_CMPNY_CD, NISS_ST_CD, GRGNG_ZIP_5, NISS_TERR_CD,
      LINE_CD, ACCDNT_YR, NISS_CVG_CD, RTNG_ZNE_CD, TERM_ZNE_CD, NISS_CLASS_CD,
      NISS_ELIG_PNTS_CD, NISS_AGE_GRP_CD, NISS_CMMCL_IND_CD, NISS_EXCPN_CD,
      NISS_FGVNS_CD, NISS_PASSV_RESTRA_CD, NISS_DEFNS_DRVR_CRD_CD, NISS_ANTI_THFT_DVC_CD,
      NISS_DAY_TM_RUN_LAMPS_DISC_CD, NISS_PLCY_LMT_CD, NISS_DEDUC_CD, NISS_SSL_LIAB_CD,
      NISS_SUBLOB_CD, NISS_TYP_LOSS_CD, NISS_LIAB_OR_NO_FAULT_CD, NISS_ANNL_STMNT_LOB_CD,
      NISS_PD_LOSS, NISS_PD_ALLOC_ADJUS_EXPNS, NISS_OUTSTNDG_LOSS, NISS_NO_PD_CLMS,
      NISS_NO_OUTSTND_CLMS, RSVD_NISS_USE, NISS_RSVD_CMPNY_USE, NISS_MNFCTRS_MDL_YR,
      PLCY_CNTRCT_NUM
    ) AS CVG_ATTR,
    -- Generate checksum using MD5
    MD5(
      CONCAT(
        CLNDR_YR, CALL_YR, NISS_CMPNY_CD, NISS_ST_CD, GRGNG_ZIP_5, NISS_TERR_CD,
        LINE_CD, ACCDNT_YR, NISS_CVG_CD, RTNG_ZNE_CD, TERM_ZNE_CD, NISS_CLASS_CD,
        NISS_ELIG_PNTS_CD, NISS_AGE_GRP_CD, NISS_CMMCL_IND_CD, NISS_EXCPN_CD,
        NISS_FGVNS_CD, NISS_PASSV_RESTRA_CD, NISS_DEFNS_DRVR_CRD_CD, NISS_ANTI_THFT_DVC_CD,
        NISS_DAY_TM_RUN_LAMPS_DISC_CD, NISS_PLCY_LMT_CD, NISS_DEDUC_CD, NISS_SSL_LIAB_CD,
        NISS_SUBLOB_CD, NISS_TYP_LOSS_CD, NISS_LIAB_OR_NO_FAULT_CD, NISS_ANNL_STMNT_LOB_CD,
        NISS_PD_LOSS, NISS_PD_ALLOC_ADJUS_EXPNS, NISS_OUTSTNDG_LOSS, NISS_NO_PD_CLMS,
        NISS_NO_OUTSTND_CLMS, RSVD_NISS_USE, NISS_RSVD_CMPNY_USE, NISS_MNFCTRS_MDL_YR,
        PLCY_CNTRCT_NUM
      )
    ) AS CVG_ATTR_CHCKSUM
  FROM source_data
),

Upd_CVG_ATTR_SK AS (
  SELECT
    NISS_APRM_DETL_SK,
    CVG_ATTR_CHCKSUM
  FROM EXP_Gen_CvgAttrCheckSum
)

SELECT *
FROM Upd_CVG_ATTR_SK