
{{ config(materialized='view') }}

WITH source_wrk_birp_niss_aprm_detl AS (
  SELECT
    *,
    CONCAT(
      TRIM(CLNDR_YR), TRIM(NISS_CMPNY_CD), TRIM(NISS_ST_CD), TRIM(GRGNG_ZIP_5), TRIM(NISS_TERR_CD), TRIM(LINE_CD), TRIM(ACCDNT_YR), TRIM(NISS_CVG_CD),
      TRIM(RTNG_ZNE_CD), TRIM(TERM_ZNE_CD), TRIM(NISS_CLASS_CD), TRIM(NISS_ELIG_PNTS_CD), CAST(NISS_AGE_GRP_CD AS STRING), TRIM(NISS_CMMCL_IND_CD), TRIM(NISS_EXCPN_CD),
      TRIM(NISS_FGVNS_CD), TRIM(NISS_PASSV_RESTRA_CD), TRIM(NISS_DEFNS_DRVR_CRD_CD), TRIM(NISS_ANTI_THFT_DVC_CD), TRIM(NISS_DAY_TM_RUN_LAMPS_DISC_CD),
      TRIM(NISS_PLCY_LMT_CD), TRIM(NISS_DEDUC_CD), TRIM(NISS_SSL_LIAB_CD), TRIM(NISS_SUBLOB_CD), TRIM(NISS_TYP_LOSS_CD), TRIM(NISS_LIAB_OR_NO_FAULT_CD),
      TRIM(NISS_ANNL_STMNT_LOB_CD), COALESCE(NISS_PD_LOSS, 0), COALESCE(NISS_PD_ALLOC_ADJUS_EXPNS, 0), COALESCE(NISS_OUTSTNDG_LOSS, 0), COALESCE(NISS_NO_PD_CLMS, 0),
      COALESCE(NISS_NO_OUTSTND_CLMS, 0), COALESCE(TRIM(RSVD_NISS_USE), '0'), TRIM(NISS_RSVD_CMPNY_USE), COALESCE(NISS_MNFCTRS_MDL_YR, 0),
      TRIM(CVG_TYP_CD), TRIM(CVG_TYP_IND)
    ) AS CVG_CD_ATTR
  FROM {{ source('GENAI_POWER_BI', 'WRK_BIRP_NISS_APRM_DETL') }}
),

source_fdr_lib_wrk_birp_niss_aprm_detl AS (
  SELECT DISTINCT
    CVG_CD_ATTR,
    ROW_NUMBER() OVER (ORDER BY CVG_CD_ATTR) AS CVG_CD_ATTR_SK
  FROM source_wrk_birp_niss_aprm_detl
),

exp_to_generate_cvg_cd_sk AS (
  SELECT
    s.NISS_APRM_DETL_SK,
    s.CVG_ATTR_SK,
    l.CVG_CD_ATTR_SK
  FROM source_wrk_birp_niss_aprm_detl s
  LEFT JOIN source_fdr_lib_wrk_birp_niss_aprm_detl l
    ON s.CVG_CD_ATTR = l.CVG_CD_ATTR
),

upd_cvg_cd_sk AS (
  SELECT
    NISS_APRM_DETL_SK,
    CVG_CD_ATTR_SK
  FROM exp_to_generate_cvg_cd_sk
)

SELECT *
FROM upd_cvg_cd_sk
