
{{ config(materialized='view') }}

WITH source_fdr_wrk_birp_niss_aprm_detl AS (
  SELECT
    NISS_APRM_DETL_SK,
    LTRIM(RTRIM(NISS_CLASS_CD)) AS NISS_CLASS_CD,
    LTRIM(RTRIM(ST_ABBR)) AS ST_ABBR,
    LTRIM(RTRIM(ST_CD)) AS ST_CD,
    LTRIM(RTRIM(RATNG_CMPY_CD)) AS RATNG_CMPY_CD,
    LTRIM(RTRIM(MLT_CAR_IND)) AS MLT_CAR_IND,
    LTRIM(RTRIM(RT_CLS)) AS RT_CLS,
    LTRIM(RTRIM(FINAL_RDRVR_AGE)) AS FINAL_RDRVR_AGE,
    LTRIM(RTRIM(GENDR)) AS GENDR,
    LTRIM(RTRIM(MRTL_STAT)) AS MRTL_STAT,
    LTRIM(RTRIM(AUTO_USE_CD)) AS AUTO_USE_CD,
    LTRIM(RTRIM(MILES_TO_WRK)) AS MILES_TO_WRK,
    LTRIM(RTRIM(GOOD_STDNT_IND)) AS GOOD_STDNT_IND,
    LTRIM(RTRIM(DRVR_TRNG_IND)) AS DRVR_TRNG_IND,
    LTRIM(RTRIM(SOI_TYP)) AS SOI_TYP,
    LTRIM(RTRIM(ACCTNG_LOB)) AS ACCTNG_LOB,
    LTRIM(RTRIM(CVG_TYP_CD)) AS CVG_TYP_CD,
    REC_EXCPN_IND,
    REC_EXCPN_RSN_DESC
  FROM {{ source('GENAI_POWER_BI', 'WRK_BIRP_NISS_APRM_DETL') }}
  WHERE ST_ABBR NOT IN ('NY', 'NJ') AND SOURCE_IND_DERIVED = 'FARMERS'
),

exp_to_drv_class_cd1 AS (
  SELECT
    *,
    CASE 
      WHEN IFNULL(AUTO_USE_CD, '') = '' THEN ''
      ELSE AUTO_USE_CD
    END AS I_AUTO_USE_CD,
    CAST(MILES_TO_WRK AS INTEGER) AS IMILES_TO_WRK,
    CASE 
      WHEN SUBSTRING(LTRIM(RTRIM(NISS_CLASS_CD)), 1, 4) = '????' OR SUBSTRING(NISS_CLASS_CD, 5, 6) = '??' THEN '??????'
      ELSE NISS_CLASS_CD
    END AS FINAL_NISS_CLASS_CD
  FROM source_fdr_wrk_birp_niss_aprm_detl
),

upd_niss_class_cd AS (
  SELECT
    NISS_APRM_DETL_SK,
    FINAL_NISS_CLASS_CD AS NISS_CLASS_CD,
    REC_EXCPN_IND,
    REC_EXCPN_RSN_DESC
  FROM exp_to_drv_class_cd1
)

SELECT *
FROM upd_niss_class_cd
