{{
  config(
    materialized='ephemeral'
  )
}}

WITH source_wrk_birp_niss_aprm_detl AS (
  SELECT *
  FROM {{ source('GENAI_POWER_BI', 'WRK_BIRP_NISS_APRM_DETL') }}
),

source_fdr_lib_wrk_birp_niss_aprm_detl AS (
  SELECT 
    NISS_APRM_DETL_SK,
    (CLNDR_YR || CALL_YR || NISS_CMPNY_CD || NISS_ST_CD || GRGNG_ZIP_5 || NISS_TERR_CD || LINE_CD || ACCDNT_YR || NISS_CVG_CD || RTNG_ZNE_CD || TERM_ZNE_CD || NISS_CLASS_CD || NISS_ELIG_PNTS_CD || NISS_AGE_GRP_CD || NISS_CMMCL_IND_CD || NISS_EXCPN_CD || NISS_FGVNS_CD || NISS_PASSV_RESTRA_CD || NISS_DEFNS_DRVR_CRD_CD || NISS_ANTI_THFT_DVC_CD || NISS_DAY_TM_RUN_LAMPS_DISC_CD || NISS_PLCY_LMT_CD || NISS_DEDUC_CD || NISS_SSL_LIAB_CD || NISS_SUBLOB_CD || NISS_TYP_LOSS_CD || NISS_LIAB_OR_NO_FAULT_CD || NISS_ANNL_STMNT_LOB_CD || NISS_PD_LOSS || NISS_PD_ALLOC_ADJUS_EXPNS || NISS_OUTSTNDG_LOSS || NISS_NO_PD_CLMS || NISS_NO_OUTSTND_CLMS || RSVD_NISS_USE || NISS_RSVD_CMPNY_USE || NISS_MNFCTRS_MDL_YR) AS CVG_ATTR
  FROM (
    SELECT 
      NISS_APRM_DETL_SK,
      TRIM(CLNDR_YR) AS CLNDR_YR,
      TRIM(CALL_YR) AS CALL_YR,
      TRIM(NISS_CMPNY_CD) AS NISS_CMPNY_CD,
      TRIM(NISS_ST_CD) AS NISS_ST_CD,
      TRIM(GRGNG_ZIP_5) AS GRGNG_ZIP_5,
      TRIM(NISS_TERR_CD) AS NISS_TERR_CD,
      TRIM(LINE_CD) AS LINE_CD,
      TRIM(ACCDNT_YR) AS ACCDNT_YR,
      TRIM(NISS_CVG_CD) AS NISS_CVG_CD,
      TRIM(RTNG_ZNE_CD) AS RTNG_ZNE_CD,
      TRIM(TERM_ZNE_CD) AS TERM_ZNE_CD,
      TRIM(NISS_CLASS_CD) AS NISS_CLASS_CD,
      TRIM(NISS_ELIG_PNTS_CD) AS NISS_ELIG_PNTS_CD,
      CAST(NISS_AGE_GRP_CD AS VARCHAR) AS NISS_AGE_GRP_CD,
      TRIM(NISS_CMMCL_IND_CD) AS NISS_CMMCL_IND_CD,
      TRIM(NISS_EXCPN_CD) AS NISS_EXCPN_CD,
      TRIM(NISS_FGVNS_CD) AS NISS_FGVNS_CD,
      TRIM(NISS_PASSV_RESTRA_CD) AS NISS_PASSV_RESTRA_CD,
      TRIM(NISS_DEFNS_DRVR_CRD_CD) AS NISS_DEFNS_DRVR_CRD_CD,
      TRIM(NISS_ANTI_THFT_DVC_CD) AS NISS_ANTI_THFT_DVC_CD,
      TRIM(NISS_DAY_TM_RUN_LAMPS_DISC_CD) AS NISS_DAY_TM_RUN_LAMPS_DISC_CD,
      TRIM(NISS_PLCY_LMT_CD) AS NISS_PLCY_LMT_CD,
      TRIM(NISS_DEDUC_CD) AS NISS_DEDUC_CD,
      TRIM(NISS_SSL_LIAB_CD) AS NISS_SSL_LIAB_CD,
      TRIM(NISS_SUBLOB_CD) AS NISS_SUBLOB_CD,
      TRIM(NISS_TYP_LOSS_CD) AS NISS_TYP_LOSS_CD,
      TRIM(NISS_LIAB_OR_NO_FAULT_CD) AS NISS_LIAB_OR_NO_FAULT_CD,
      TRIM(NISS_ANNL_STMNT_LOB_CD) AS NISS_ANNL_STMNT_LOB_CD,
      CAST(NISS_PD_LOSS AS VARCHAR) AS NISS_PD_LOSS,
      CAST(NISS_PD_ALLOC_ADJUS_EXPNS AS VARCHAR) AS NISS_PD_ALLOC_ADJUS_EXPNS,
      CAST(NISS_OUTSTNDG_LOSS AS VARCHAR) AS NISS_OUTSTNDG_LOSS,
      CAST(NISS_NO_PD_CLMS AS VARCHAR) AS NISS_NO_PD_CLMS,
      CAST(NISS_NO_OUTSTND_CLMS AS VARCHAR) AS NISS_NO_OUTSTND_CLMS,
      TRIM(RSVD_NISS_USE) AS RSVD_NISS_USE,
      TRIM(NISS_RSVD_CMPNY_USE) AS NISS_RSVD_CMPNY_USE,
      CAST(NISS_MNFCTRS_MDL_YR AS VARCHAR) AS NISS_MNFCTRS_MDL_YR
    FROM {{ source('GENAI_POWER_BI', 'WRK_BIRP_NISS_APRM_DETL') }}
  ) AS subquery
),

exp_gen_cvg_attr_checksum AS (
  SELECT 
    NISS_APRM_DETL_SK,
    CVG_ATTR,
    MD5(CVG_ATTR) AS CVG_ATTR_CHCKSUM
  FROM source_fdr_lib_wrk_birp_niss_aprm_detl
),

srt_order_by_checksum AS (
  SELECT 
    NISS_APRM_DETL_SK,
    CVG_ATTR_CHCKSUM
  FROM exp_gen_cvg_attr_checksum
  ORDER BY CVG_ATTR_CHCKSUM ASC
),

exp_gen_cvg_attr_sk AS (
  SELECT 
    NISS_APRM_DETL_SK,
    CVG_ATTR_CHCKSUM,
    LAG(CVG_ATTR_CHCKSUM) OVER (ORDER BY CVG_ATTR_CHCKSUM) AS v_CVG_ATTR_CHCKSUM_Prev,
    CVG_ATTR_CHCKSUM AS v_CVG_ATTR_CHCKSUM_Curr,
    CASE 
      WHEN LAG(CVG_ATTR_CHCKSUM) OVER (ORDER BY CVG_ATTR_CHCKSUM) = CVG_ATTR_CHCKSUM THEN 'N'
      ELSE 'Y'
    END AS v_CVG_ATTR_CHCKSUM_NewValInd,
    CASE 
      WHEN LAG(CVG_ATTR_CHCKSUM) OVER (ORDER BY CVG_ATTR_CHCKSUM) = CVG_ATTR_CHCKSUM THEN NULL
      ELSE ROW_NUMBER() OVER (ORDER BY CVG_ATTR_CHCKSUM)
    END AS CVG_ATTR_SK
  FROM srt_order_by_checksum
),

upd_cvg_attr_sk AS (
  SELECT 
    NISS_APRM_DETL_SK,
    CVG_ATTR_SK,
    CVG_ATTR_CHCKSUM
  FROM exp_gen_cvg_attr_sk
)

SELECT *
FROM upd_cvg_attr_sk