{{
  config(materialized='ephemeral')
}}

WITH EXP_PassThru AS (
  -- Node: EXP_PassThru
  SELECT
    NISS_APRM_DETL_SK,
    ST_ABBR,
    ACCTNG_LOB,
    CVG_TYP_CD,
    CVG_AMT,
    PRD_GRP_CD,
    COMP_DED,
    COLL_DED
  FROM {{ source('genai_power_bi', 'WRK_BIRP_NISS_APRM_DETL') }}
),

EXP_CvgAmount_Split AS (
  -- Node: EXP_CvgAmount_Split
  SELECT
    *,
    REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '') AS v_CVG_AMT,
    LENGTH(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '')) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', ''), '/', '')) + 1 AS v_CVG_AMT_Parts,
    POSITION('/' IN REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '')) AS v_CVG_AMT_Part1_Pos,
    POSITION('/' IN REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '') FROM POSITION('/' IN REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '') + 1) AS v_CVG_AMT_Part2_Pos,
    CASE 
      WHEN LENGTH(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '')) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', ''), '/', '')) + 1 = 1 THEN REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '')
      WHEN LENGTH(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '')) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', ''), '/', '')) + 1 = 2 THEN SUBSTRING(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '') FROM 1 FOR POSITION('/' IN REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '') - 1)
      WHEN LENGTH(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '')) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', ''), '/', '')) + 1 = 3 THEN SUBSTRING(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '') FROM 1 FOR POSITION('/' IN REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '') - 1)
      ELSE '0'
    END AS v_AMOUNT_FIELD1,
    CASE 
      WHEN LENGTH(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '')) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', ''), '/', '')) + 1 = 1 THEN '0'
      WHEN LENGTH(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '')) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', ''), '/', '')) + 1 = 2 THEN SUBSTRING(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '') FROM POSITION('/' IN REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '') + 1)
      WHEN LENGTH(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '')) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', ''), '/', '')) + 1 = 3 THEN SUBSTRING(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '') FROM POSITION('/' IN REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '') + 1 FOR POSITION('/' IN REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '') FROM POSITION('/' IN REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '') + 1) - POSITION('/' IN REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '') - 1)
      ELSE '0'
    END AS v_AMOUNT_FIELD2,
    CASE 
      WHEN LENGTH(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '')) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', ''), '/', '')) + 1 = 1 THEN '0'
      WHEN LENGTH(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '')) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', ''), '/', '')) + 1 = 2 THEN '0'
      WHEN LENGTH(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '')) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', ''), '/', '')) + 1 = 3 THEN SUBSTRING(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '') FROM POSITION('/' IN REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '') FROM POSITION('/' IN REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '') + 1) + 1)
      ELSE '0'
    END AS v_AMOUNT_FIELD3,
    CAST(v_AMOUNT_FIELD1 AS DECIMAL) AS CVG_AMT_1_Decimal,
    CAST(v_AMOUNT_FIELD2 AS DECIMAL) AS CVG_AMT_2_Decimal,
    CAST(v_AMOUNT_FIELD3 AS DECIMAL) AS CVG_AMT_3_Decimal,
    LENGTH(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '')) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', ''), '/', '')) + 1 AS CVG_AMT_NO_OF_PARTS,
    REPLACE(LTRIM(RTRIM(CVG_AMT)), ',', '') AS SRC_CVG_AMT
  FROM EXP_PassThru
),

EXP_Derive_NISS_PLCY_LMT_CD_And_PassThru AS (
  -- Node: EXP_Derive_NISS_PLCY_LMT_CD_And_PassThru
  SELECT
    *,
    CASE 
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT = '10,000/10,000' AND PRD_GRP_CD = 'BA' THEN '28'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT IN ('15,000/30,000','15,000/1,000', '15,000/2,000', '15,000/2,500', '15,000/250','15,000/250') THEN '10'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT = '20,000/30,000' THEN '11'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT = '20,000/40,000' THEN '12'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT IN ('25,000/50,000','25,000/500') THEN '13'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT = '35,000/35,000' THEN '14'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT IN ('50,000/100,000','50,000/2,500','50,000/500') THEN '15'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT IN ('100,000/200,000','100,000/500') THEN '16'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT = '100,000/300,000' THEN '17'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT = '300,000/300,000' THEN '18'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT IN ('250,000/500,000','250,000/1,000','250,000/2,500', '250,000/250', '250,000/500') THEN '19'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT = '300,000/500,000' THEN '29'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT IN ('500,000/500,000','500,000/500') THEN '20'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT = '500,000/1,000,000' THEN '21'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT = '1,000,000/1,000,000' THEN '22'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT = '1,000,000/2,000,000' THEN '23'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT = '1,500,000/3,000,000' THEN '24'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT = '2,500,000/5,000,000' THEN '25'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT = '5,000,000/10,000,000' THEN '26'
      WHEN ST_ABBR = 'NJ' AND ACCTNG_LOB = '192BI' AND CVG_AMT = '10,000,000/10,000,000' THEN '27'
      ELSE '??'
    END AS v_NISS_PLCY_LMT_CD_NewJersey
  FROM EXP_CvgAmount_Split
),

UPD_NISS_PLCY_LMT_CD AS (
  -- Node: UPD_NISS_PLCY_LMT_CD
  SELECT
    NISS_APRM_DETL_SK,
    v_NISS_PLCY_LMT_CD_NewJersey AS NISS_PLCY_LMT_CD,
    NULL AS NISS_DEDUC_CD
  FROM EXP_Derive_NISS_PLCY_LMT_CD_And_PassThru
)

SELECT * FROM UPD_NISS_PLCY_LMT_CD;