{{
  config(materialized='ephemeral')
}}

WITH EXP_defaults AS (
  SELECT
    NISS_CMPNY_CD,
    CLNDR_YR,
    CALL_YR,
    NISS_ST_CD,
    LINE_CD,
    ACCDNT_YR,
    NISS_CVG_CD,
    NISS_TERR_CD,
    RTNG_ZNE_CD,
    TERM_ZNE_CD,
    GRGNG_ZIP_5,
    NISS_CLASS_CD,
    NISS_ELIG_PNTS_CD,
    NISS_AGE_GRP_CD,
    NISS_MNFCTRS_MDL_YR
  FROM {{ source('genai_power_bi', 'WRK_BIRP_NISS_APRM_DETL') }}
),

EXP_PASS_FINAL_Txt AS (
  SELECT
    '',
    NISS_CMPNY_CD,
    NULL AS CLNDR_YR,
    SUBSTRING(TRIM(CLNDR_YR), 3, 2) AS o_CLNDR_YR,
    NULL AS CALL_YR,
    SUBSTRING(TRIM(CALL_YR), 3, 2) AS o_REG_PRD_YR,
    NISS_ST_CD,
    LINE_CD,
    ACCDNT_YR,
    NULL AS NISS_CVG_CD,
    CASE 
      WHEN TRIM(NISS_CVG_CD) = '' THEN '???'
      ELSE NISS_CVG_CD
    END AS o_NISS_CVG_CD,
    NULL AS NISS_TERR_CD,
    CASE 
      WHEN TRIM(NISS_TERR_CD) = '' OR NISS_TERR_CD IS NULL THEN '???'
      ELSE NISS_TERR_CD
    END AS o_NISS_TERR_CD
  FROM EXP_defaults
),

EXP_PASS_FINAL_Csv AS (
  SELECT
    '',
    NISS_CMPNY_CD,
    NULL AS CLNDR_YR,
    SUBSTRING(TRIM(CLNDR_YR), 3, 2) AS o_CLNDR_YR,
    NULL AS CALL_YR,
    SUBSTRING(TRIM(CALL_YR), 3, 2) AS o_REG_PRD_YR,
    NISS_ST_CD,
    LINE_CD,
    ACCDNT_YR,
    NULL AS NISS_CVG_CD,
    CASE 
      WHEN TRIM(NISS_CVG_CD) = '' THEN '???'
      ELSE NISS_CVG_CD
    END AS o_NISS_CVG_CD,
    NULL AS NISS_TERR_CD,
    CASE 
      WHEN TRIM(NISS_TERR_CD) = '' OR NISS_TERR_CD IS NULL THEN '???'
      ELSE NISS_TERR_CD
    END AS o_NISS_TERR_CD
  FROM EXP_defaults
),

EXP_GenErrReason AS (
  SELECT
    i_REC_DROP_RSN_DESC,
    POSITION(';' IN i_REC_DROP_RSN_DESC) AS v_REC_DROP_RSN_DESC_POS1,
    POSITION(';' IN i_REC_DROP_RSN_DESC FROM POSITION(';' IN i_REC_DROP_RSN_DESC) + 1) AS v_REC_DROP_RSN_DESC_POS2,
    POSITION(';' IN i_REC_DROP_RSN_DESC FROM POSITION(';' IN i_REC_DROP_RSN_DESC FROM POSITION(';' IN i_REC_DROP_RSN_DESC) + 1) + 1) AS v_REC_DROP_RSN_DESC_POS3,
    4 AS v_REC_DROP_RSN_DESC_COUNT,
    LTRIM(RTRIM(SUBSTRING(i_REC_DROP_RSN_DESC, 1, POSITION(';' IN i_REC_DROP_RSN_DESC) - 1))) AS v_REC_DROP_RSN_DESC1,
    LTRIM(RTRIM(SUBSTRING(i_REC_DROP_RSN_DESC, POSITION(';' IN i_REC_DROP_RSN_DESC) + 1, POSITION(';' IN i_REC_DROP_RSN_DESC FROM POSITION(';' IN i_REC_DROP_RSN_DESC) + 1) - POSITION(';' IN i_REC_DROP_RSN_DESC) - 1))) AS v_REC_DROP_RSN_DESC2,
    LTRIM(RTRIM(SUBSTRING(i_REC_DROP_RSN_DESC, POSITION(';' IN i_REC_DROP_RSN_DESC FROM POSITION(';' IN i_REC_DROP_RSN_DESC) + 1) + 1, POSITION(';' IN i_REC_DROP_RSN_DESC FROM POSITION(';' IN i_REC_DROP_RSN_DESC FROM POSITION(';' IN i_REC_DROP_RSN_DESC) + 1) + 1) - POSITION(';' IN i_REC_DROP_RSN_DESC FROM POSITION(';' IN i_REC_DROP_RSN_DESC) + 1) - 1))) AS v_REC_DROP_RSN_DESC3,
    LTRIM(RTRIM(SUBSTRING(i_REC_DROP_RSN_DESC, POSITION(';' IN i_REC_DROP_RSN_DESC FROM POSITION(';' IN i_REC_DROP_RSN_DESC FROM POSITION(';' IN i_REC_DROP_RSN_DESC) + 1) + 1) + 1))) AS v_REC_DROP_RSN_DESC4,
    SUBSTRING(i_REC_DROP_RSN_DESC, 1, 3) AS REC_DROP_RSN_DESC
  FROM EXP_defaults
),

EXP_PASS_DETL AS (
  SELECT
    NULL AS CLNDR_YR,
    SUBSTRING(TRIM(CLNDR_YR), 3, 2) AS o_CLNDR_YR,
    NULL AS CALL_YR,
    SUBSTRING(TRIM(CALL_YR), 3, 2) AS o_CALL_YR,
    NAIC_CMPNY_CD,
    NISS_CMPNY_CD,
    ST_NM,
    ST_CD,
    NISS_ST_CD,
    ST_ABBR,
    ACCTNG_LOB,
    CVG_TYP_CD,
    CVG_TYP_IND,
    NULL AS CVG_AMT,
    REPLACE(TRIM(CVG_AMT), ',', '') AS o_CVG_AMT
  FROM EXP_defaults
),

EXP_PASS_TRGT AS (
  SELECT
    NULL AS CLNDR_YR,
    SUBSTRING(TRIM(CLNDR_YR), 3, 2) AS o_CLNDR_YR,
    NULL AS CALL_YR,
    SUBSTRING(TRIM(CALL_YR), 3, 2) AS o_CALL_YR,
    NAIC_CMPNY_CD,
    NISS_CMPNY_CD,
    ST_NM,
    ST_CD,
    NISS_ST_CD,
    ST_ABBR,
    ACCTNG_LOB,
    CVG_TYP_CD,
    NULL AS CVG_AMT,
    REPLACE(TRIM(CVG_AMT), ',', '') AS o_CVG_AMT
  FROM EXP_defaults
),

EX_PASS_SUMRY AS (
  SELECT
    NISS_CMPNY_CD,
    NULL AS CLNDR_YR,
    SUBSTRING(TRIM(CLNDR_YR), 3, 2) AS o_CLNDR_YR,
    NISS_ST_CD,
    ACCDNT_YR,
    NULL AS NISS_CVG_CD,
    CASE 
      WHEN TRIM(NISS_CVG_CD) = '' THEN '???'
      ELSE NISS_CVG_CD
    END AS o_NISS_CVG_CD,
    NISS_TERR_CD,
    NULL AS NISS_CLASS_CD,
    CASE 
      WHEN TRIM(NISS_CLASS_CD) = '' THEN '??????'
      ELSE NISS_CLASS_CD
    END AS o_NISS_CLASS_CD,
    NISS_SUBLOB_CD,
    NISS_TYP_LOSS_CD,
    NISS_ANNL_STMNT_LOB_CD,
    CVG_EXPS_VAL,
    TTL_WRITTN_PREM_AMT,
    NISS_PD_LOSS,
    NISS_PD_ALLOC_ADJUS_EXPNS,
    NISS_OUTSTNDG_LOSS,
    NISS_NO_PD_CLMS,
    NISS_NO_OUTSTND_CLMS,
    TALLY
  FROM EXP_defaults
)

SELECT * FROM EX_PASS_SUMRY;