{{ config(materialized='ephemeral') }}

WITH source_data AS (
  SELECT 
    NISS_APRM_DETL_SK,
    ST_ABBR,
    AUTO_USE_CD,
    IAGE,
    GENDR,
    MRTL_STAT,
    GOOD_STDNT_IND,
    DRVR_TRNG_IND,
    IMILES_TO_WRK
  FROM {{ source('genai_power_bi', 'WRK_BIRP_NISS_APRM_DETL') }}
),

-- Node: EXP_To_Drv_Class_Cd
exp_to_drv_class_cd AS (
  SELECT
    *,
    CASE 
      WHEN ST_ABBR = 'NJ' AND AUTO_USE_CD IN ('PLS', 'STG', '') AND IAGE >= 75 THEN '8031'
      WHEN ST_ABBR = 'NJ' AND AUTO_USE_CD IN ('PLS', 'STG', '') AND IAGE >= 65 AND IAGE < 75 THEN '8021'
      WHEN ST_ABBR = 'NJ' AND AUTO_USE_CD IN ('PLS', 'STG', '') AND ((IAGE >= 30 AND IAGE < 65) OR TRIM(AGE) = '') AND GENDR = 'F' THEN '8131'
      WHEN ST_ABBR = 'NJ' AND AUTO_USE_CD IN ('PLS', 'STG', '') AND (IAGE >= 30 AND IAGE < 65) AND (GENDR = 'U' OR TRIM(GENDR) = '') THEN '8131'
      WHEN ST_ABBR = 'NJ' AND AUTO_USE_CD IN ('PLS', 'STG', '') AND (IAGE >= 25 AND IAGE < 30) AND (GENDR = 'U' OR TRIM(GENDR) = '') AND (MRTL_STAT = 'S' OR TRIM(MRTL_STAT) = '') THEN '8111'
      WHEN ST_ABBR = 'NJ' AND AUTO_USE_CD = 'COM' AND (IAGE >= 30 AND IAGE < 65) AND (GENDR = 'U' OR TRIM(GENDR) = '') AND (MRTL_STAT = 'S' OR TRIM(MRTL_STAT) = '') THEN '8132'
      WHEN ST_ABBR = 'NJ' AND AUTO_USE_CD IN ('COM', 'SLS') AND IAGE < 18 AND (GENDR = 'U' OR TRIM(GENDR) = '') AND (MRTL_STAT = 'S' OR TRIM(MRTL_STAT) = '') AND GOOD_STDNT_IND = 'N' AND DRVR_TRNG_IND = 'N' THEN '8212'
      WHEN ST_ABBR = 'NJ' AND AUTO_USE_CD IN ('PLS', 'STG', '') AND IAGE = 18 AND (GENDR = 'U' OR TRIM(GENDR) = '') AND (MRTL_STAT = 'S' OR TRIM(MRTL_STAT) = '') AND GOOD_STDNT_IND = 'Y' AND DRVR_TRNG_IND = 'N' THEN '8224'
      WHEN ST_ABBR = 'NJ' AND AUTO_USE_CD IN ('PLS', 'STG', '') AND IAGE = 19 AND (GENDR = 'U' OR TRIM(GENDR) = '') AND (MRTL_STAT = 'S' OR TRIM(MRTL_STAT) = '') AND GOOD_STDNT_IND != 'Y' AND DRVR_TRNG_IND = 'N' THEN '8231'
      WHEN ST_ABBR = 'NJ' AND AUTO_USE_CD IN ('PLS', 'STG', '') AND IAGE = 19 AND (GENDR = 'U' OR TRIM(GENDR) = '') AND (MRTL_STAT = 'S' OR TRIM(MRTL_STAT) = '') AND GOOD_STDNT_IND = 'Y' AND DRVR_TRNG_IND = 'N' THEN '8234'
      WHEN ST_ABBR = 'NJ' AND AUTO_USE_CD IN ('PLS', 'STG', '') AND IAGE = 20 AND (GENDR = 'U' OR TRIM(GENDR) = '') AND (MRTL_STAT = 'S' OR TRIM(MRTL_STAT) = '') AND GOOD_STDNT_IND != 'Y' AND DRVR_TRNG_IND = 'N' THEN '8241'
      WHEN ST_ABBR = 'NJ' AND AUTO_USE_CD IN ('PLS', 'STG', '') AND IAGE = 20 AND (GENDR = 'U' OR TRIM(GENDR) = '') AND (MRTL_STAT = 'S' OR TRIM(MRTL_STAT) = '') AND GOOD_STDNT_IND = 'Y' AND DRVR_TRNG_IND = 'N' THEN '8244'
      WHEN ST_ABBR = 'NJ' AND AUTO_USE_CD IN ('PLS', 'STG', '') AND (IAGE > 20 AND IAGE < 25) AND (GENDR = 'U' OR TRIM(GENDR) = '') AND (MRTL_STAT = 'S' OR TRIM(MRTL_STAT) = '') AND GOOD_STDNT_IND != 'Y' AND DRVR_TRNG_IND = 'N' THEN '8461'
      WHEN ST_ABBR = 'NJ' AND AUTO_USE_CD IN ('PLS', 'STG', '') AND (IAGE > 20 AND IAGE < 25) AND (GENDR = 'U' OR TRIM(GENDR) = '') AND (MRTL_STAT = 'S' OR TRIM(MRTL_STAT) = '') AND GOOD_STDNT_IND = 'Y' AND DRVR_TRNG_IND = 'N' THEN '8464'
      ELSE '????'
    END AS v_CLASS_CD_Primary_NJ_1
  FROM source_data
),

-- Node: UPD_NISS_CLASS_CD
upd_niss_class_cd AS (
  SELECT
    NISS_APRM_DETL_SK,
    v_CLASS_CD_Primary_NJ_1 AS NISS_CLASS_CD,
    NULL AS REC_EXCP_IND,
    NULL AS REC_EXCP_DESC
  FROM exp_to_drv_class_cd
)

SELECT * FROM upd_niss_class_cd;