{{
  config(materialized='ephemeral')
}}

WITH EXP_BILimit_Split AS (
  SELECT
    BI_LMT,
    REPLACE(LTRIM(RTRIM(BI_LMT)), ',', '') AS v_BI_LMT,
    LENGTH(LTRIM(RTRIM(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', '')))) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''), '/', '')) + 1 AS v_BI_LMT_Parts,
    POSITION('/' IN REPLACE(LTRIM(RTRIM(BI_LMT)), ',', '')) AS v_BI_LMT_Part1_Pos,
    POSITION('/' IN REPLACE(LTRIM(RTRIM(BI_LMT)), ',', '') FROM POSITION('/' IN REPLACE(LTRIM(RTRIM(BI_LMT)), ',', '')) + 1) AS v_BI_LMT_Part2_Pos,
    CASE 
      WHEN LENGTH(LTRIM(RTRIM(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''))) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''), '/', '')) + 1) = 1 THEN REPLACE(LTRIM(RTRIM(BI_LMT)), ',', '')
      WHEN LENGTH(LTRIM(RTRIM(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''))) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''), '/', '')) + 1) = 2 THEN SUBSTRING(LTRIM(RTRIM(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''))), 1, POSITION('/' IN REPLACE(LTRIM(RTRIM(BI_LMT)), ',', '')) - 1)
      WHEN LENGTH(LTRIM(RTRIM(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''))) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''), '/', '')) + 1) = 3 THEN SUBSTRING(LTRIM(RTRIM(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''))), 1, POSITION('/' IN REPLACE(LTRIM(RTRIM(BI_LMT)), ',', '')) - 1)
      ELSE '0'
    END AS v_Limit_FIELD1,
    CASE 
      WHEN LENGTH(LTRIM(RTRIM(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''))) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''), '/', '')) + 1) = 1 THEN '0'
      WHEN LENGTH(LTRIM(RTRIM(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''))) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''), '/', '')) + 1) = 2 THEN SUBSTRING(LTRIM(RTRIM(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''))), POSITION('/' IN REPLACE(LTRIM(RTRIM(BI_LMT)), ',', '')) + 1)
      WHEN LENGTH(LTRIM(RTRIM(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''))) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''), '/', '')) + 1) = 3 THEN SUBSTRING(LTRIM(RTRIM(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''))), POSITION('/' IN REPLACE(LTRIM(RTRIM(BI_LMT)), ',', '')) + 1, POSITION('/' IN REPLACE(LTRIM(RTRIM(BI_LMT)), ',', '') FROM POSITION('/' IN REPLACE(LTRIM(RTRIM(BI_LMT)), ',', '')) + 1) - POSITION('/' IN REPLACE(LTRIM(RTRIM(BI_LMT)), ',', '')) - 1)
      ELSE '0'
    END AS v_Limit_FIELD2,
    CASE 
      WHEN LENGTH(LTRIM(RTRIM(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''))) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''), '/', '')) + 1) = 1 THEN '0'
      WHEN LENGTH(LTRIM(RTRIM(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''))) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''), '/', '')) + 1) = 2 THEN '0'
      WHEN LENGTH(LTRIM(RTRIM(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''))) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''), '/', '')) + 1) = 3 THEN SUBSTRING(LTRIM(RTRIM(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''))), POSITION('/' IN REPLACE(LTRIM(RTRIM(BI_LMT)), ',', '') FROM POSITION('/' IN REPLACE(LTRIM(RTRIM(BI_LMT)), ',', '')) + 1) + 1)
      ELSE '0'
    END AS v_Limit_FIELD3,
    CAST(v_Limit_FIELD1 AS DECIMAL) AS BI_LMT_1_Decimal,
    CAST(v_Limit_FIELD2 AS DECIMAL) AS BI_LMT_2_Decimal,
    CAST(v_Limit_FIELD3 AS DECIMAL) AS BI_LMT_3_Decimal,
    LENGTH(LTRIM(RTRIM(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''))) - LENGTH(REPLACE(REPLACE(LTRIM(RTRIM(BI_LMT)), ',', ''), '/', '')) + 1) AS BI_LMT_NO_OF_PARTS,
    REPLACE(LTRIM(RTRIM(BI_LMT)), ',', '') AS SRC_BI_LMT
  FROM {{ source('genai_power_bi', 'WRK_BIRP_NISS_APRM_DETL') }}
),

EXP_Derive_NISS_SUBLOB_CD_And_PassThru AS (
  SELECT
    NISS_APRM_DETL_SK,
    EFF_DT,
    DECODE(1, MI_PPO_IND = 1, 'Y', MI_PPO_IND = 0, 'N', '') AS v_MI_PPO_IND,
    DECODE(1,
      ST_ABBR = 'NH', '8',
      ST_ABBR = 'PA' AND SUBSTRING(ACCTNG_LOB, 1, 3) IN ('191', '192') AND LMT_TORT != '1' AND CVG_TYP_CD IN ('13000', '13006', '13007', '13008'), '4',
      ST_ABBR = 'PA' AND SUBSTRING(ACCTNG_LOB, 1, 3) IN ('191', '192') AND LMT_TORT != '1' AND CVG_TYP_CD NOT IN ('13000', '13006', '13007', '13008'), '5',
      ST_ABBR = 'PA' AND SUBSTRING(ACCTNG_LOB, 1, 3) IN ('191', '192') AND LMT_TORT = '1' AND CVG_TYP_CD IN ('13000', '13006', '13007', '13008'), '6',
      ST_ABBR = 'PA' AND SUBSTRING(ACCTNG_LOB, 1, 3) IN ('191', '192') AND LMT_TORT = '1' AND CVG_TYP_CD NOT IN ('13000', '13006', '13007', '13008'), '7',
      ST_ABBR = 'KY' AND SUBSTRING(ACCTNG_LOB, 1, 3) IN ('191', '192') AND CVG_TYP_CD = '35028' AND BI_LMT_NO_OF_PARTS = 1 AND BI_LMT_1_Decimal > 0, '3',
      ST_ABBR = 'KY' AND SUBSTRING(ACCTNG_LOB, 1, 3) IN ('191', '192') AND CVG_TYP_CD = '35028' AND (BI_LMT = '0' OR BI_LMT_NO_OF_PARTS > 1), '4',
      ST_ABBR = 'KY' AND SUBSTRING(ACCTNG_LOB, 1, 3) IN ('191', '192') AND LMT_TORT != '#' AND NOT ISNULL(LMT_TORT) AND CVG_TYP_CD IN ('13000', '13006', '13007', '13008'), '3',
      ST_ABBR = 'KY' AND SUBSTRING(ACCTNG_LOB, 1, 3) IN ('191', '192') AND (LMT_TORT = '#' OR ISNULL(LMT_TORT)) AND CVG_TYP_CD NOT IN ('13000', '13006', '13007', '13008'), '1',
      ST_ABBR = 'FL' AND SUBSTRING(ACCTNG_LOB, 1, 3) IN ('191', '192') AND CVG_TYP_CD IN ('13000', '13006', '13007', '13008'), '2',
      ST_ABBR IN ('CT', 'KS', 'MD', 'MI', 'MN', 'ND', 'OR', 'UT', 'WA') AND SUBSTRING(ACCTNG_LOB, 1, 3) IN ('191', '192') AND v_MI_PPO_IND = 'Y' AND CVG_TYP_CD IN ('13000', '13006', '13007', '13008'), '6',
      ST_ABBR IN ('KY', 'PA', 'CT', 'KS', 'MD', 'MI', 'MN', 'ND', 'OR', 'UT', 'WA', 'FL') AND SUBSTRING(ACCTNG_LOB, 1, 3) = '211', '0',
      '?'
    ) AS vv_NISS_SUBLOB_CD,
    IIF(ST_ABBR = 'MI' AND SUBSTRING(LTRIM(RTRIM(ACCTNG_LOB)), 1, 3) = '191' AND EFF_DT >= TO_DATE('07/01/2020', 'MM/DD/YYYY'),
      DECODE(1,
        CVG_TYP_CD IN ('35000', '35082') AND BI_LMT_NO_OF_PARTS = 1 AND BI_LMT_1_Decimal > 0, '2',
        CVG_TYP_CD IN ('35000', '35082') AND (BI_LMT = '0' OR BI_LMT_NO_OF_PARTS > 1), '1',
        BI_LMT_NO_OF_PARTS = 1 AND BI_LMT_1_Decimal > 0 AND CVG_TYP_CD NOT IN ('35000', '35082'), '8',
        CVG_TYP_CD NOT IN ('35000', '35082') AND (BI_LMT = '0' OR BI_LMT_NO_OF_PARTS > 1), '7',
        '?'
      ),
      vv_NISS_SUBLOB_CD
    ) AS v_NISS_SUBLOB_CD,
    IIF(v_NISS_SUBLOB_CD = '', '?', v_NISS_SUBLOB_CD) AS NISS_SUBLOB_CD
  FROM EXP_BILimit_Split
),

UPD_NISS_SUBLOB_CD AS (
  SELECT
    NISS_APRM_DETL_SK,
    NISS_SUBLOB_CD
  FROM EXP_Derive_NISS_SUBLOB_CD_And_PassThru
)

SELECT * FROM UPD_NISS_SUBLOB_CD;