{{
  config(
    materialized='ephemeral'
  )
}}

WITH source_data AS (
  SELECT * 
  FROM {{ source('DBA_COMMON_UTILS', 'ABC_BAL_ROW_COUNTS') }}
),

upd_ABC_BAL_DETAIL_AMTS_RP_INSERT AS (
  SELECT
    BAL_ROW_COUNTS_SK,
    WRKFL_CMPNT_OBJ_ID,
    FIN_DETAIL_AMT
  FROM source_data
),

upd_ABC_BAL_DETAIL_AMTS_SOURCE_UPDATE AS (
  SELECT
    BAL_ROW_COUNTS_SK,
    WRKFL_CMPNT_OBJ_ID,
    FIN_DETAIL_AMT
  FROM source_data
),

upd_ABC_BAL_DETAIL_AMTS_SOURCE_INSERT AS (
  SELECT
    BAL_ROW_COUNTS_SK,
    WRKFL_CMPNT_OBJ_ID,
    FIN_DETAIL_AMT
  FROM source_data
),

upd_ABC_BAL_DETAIL_AMTS_TARGET_INSERT_UPDATE AS (
  SELECT
    BAL_ROW_COUNTS_SK,
    WRKFL_CMPNT_OBJ_ID,
    FIN_DETAIL_AMT
  FROM source_data
)

SELECT * FROM upd_ABC_BAL_DETAIL_AMTS_TARGET_INSERT_UPDATE