{{
  config(
    materialized='ephemeral'
  )
}}

WITH upd_ABC_BAL_DETAIL_AMTS_RP_INSERT AS (
  SELECT
    BAL_ROW_COUNTS_SK,
    WRKFL_CMPNT_OBJ_ID,
    FIN_DETAIL_AMT,
    0 AS TRANSFORMATION_EXPRESSION
  FROM { source('source_system', 'source_table') }
),
upd_ABC_BAL_DETAIL_AMTS_SOURCE_UPDATE AS (
  SELECT
    BAL_ROW_COUNTS_SK,
    WRKFL_CMPNT_OBJ_ID,
    FIN_DETAIL_AMT,
    0 AS TRANSFORMATION_EXPRESSION
  FROM upd_ABC_BAL_DETAIL_AMTS_RP_INSERT
),
upd_ABC_BAL_DETAIL_AMTS_SOURCE_INSERT AS (
  SELECT
    BAL_ROW_COUNTS_SK,
    WRKFL_CMPNT_OBJ_ID,
    FIN_DETAIL_AMT,
    0 AS TRANSFORMATION_EXPRESSION
  FROM upd_ABC_BAL_DETAIL_AMTS_SOURCE_UPDATE
),
upd_ABC_BAL_DETAIL_AMTS_TARGET_INSERT_UPDATE AS (
  SELECT
    BAL_ROW_COUNTS_SK,
    WRKFL_CMPNT_OBJ_ID,
    FIN_DETAIL_AMT,
    0 AS TRANSFORMATION_EXPRESSION
  FROM upd_ABC_BAL_DETAIL_AMTS_SOURCE_INSERT
),
upd_FACESHEET_DT AS (
  SELECT
    SRC_PLCY_ID_SK,
    SRC_INSERT_TRANS_TMSP,
    SRC_EFF_DT,
    o_DERIVED_FACESHEET_PRINT_DT,
    CR_BY_MAPNG_ID,
    DW_CR_TMSP,
    UPD_BY_MAPNG_ID,
    DW_UPD_TMSP,
    WRK_FLOW_RUN_ID,
    'DD_UPDATE' AS TRANSFORMATION_EXPRESSION
  FROM upd_ABC_BAL_DETAIL_AMTS_TARGET_INSERT_UPDATE
),
upd_REPROC_INSERT AS (
  SELECT
    TFPLCY_TRAN_RESULT_SK4,
    LAT_DATE4,
    LAT_TIME4,
    LAT_ACTION4,
    STG_CR_BY_MAPNG_ID4,
    STG_DW_CR_TMSP4,
    STG_UPD_BY_MAPNG_ID4,
    STG_DW_UPD_TMSP4,
    STG_WRK_FLOW_RUN_ID4,
    POLICY_NUMBER4,
    APPLIED_DTSTMP4,
    'DD_INSERT' AS TRANSFORMATION_EXPRESSION
  FROM upd_FACESHEET_DT
),
upd_SOURCE_INSERT AS (
  SELECT
    BAL_ROW_COUNTS_SK,
    PROC_CD,
    o_RECRD_CNT_QTY,
    TFPLCY_TRAN_RESULT_SK1,
    LAT_DATE1,
    LAT_TIME1,
    LAT_ACTION1,
    STG_CR_BY_MAPNG_ID1,
    STG_DW_CR_TMSP1,
    STG_UPD_BY_MAPNG_ID1,
    STG_DW_UPD_TMSP1,
    STG_WRK_FLOW_RUN_ID1,
    'DD_INSERT' AS TRANSFORMATION_EXPRESSION
  FROM upd_REPROC_INSERT
),
upd_SOURCE_UPDATE_INSERT AS (
  SELECT
    TFPLCY_TRAN_RESULT_SK3,
    LAT_DATE3,
    LAT_TIME3,
    LAT_ACTION3,
    STG_CR_BY_MAPNG_ID3,
    STG_DW_CR_TMSP3,
    STG_UPD_BY_MAPNG_ID3,
    STG_DW_UPD_TMSP3,
    STG_WRK_FLOW_RUN_ID3,
    POLICY_NUMBER3,
    'DD_INSERT' AS TRANSFORMATION_EXPRESSION
  FROM upd_SOURCE_INSERT
),
upd_INSERT AS (
  SELECT
    TFPLCY_TRAN_RESULT_SK1,
    LAT_DATE1,
    LAT_TIME1,
    LAT_ACTION1,
    STG_CR_BY_MAPNG_ID1,
    STG_DW_CR_TMSP1,
    STG_UPD_BY_MAPNG_ID1,
    STG_DW_UPD_TMSP1,
    STG_WRK_FLOW_RUN_ID1,
    POLICY_NUMBER1,
    'DD_INSERT' AS TRANSFORMATION_EXPRESSION
  FROM upd_SOURCE_UPDATE_INSERT
)

SELECT *
FROM upd_INSERT;