WITH audit_details AS (
    SELECT
        MAPPING_NAME,
        FOLDER_NAME,
        WORKFLOW_NAME,
        ROW_NUMBER() OVER (ORDER BY MAPPING_NAME) AS v_RECORD_NUM,
        v_MAPNG_ID AS CR_BY_MAPNG_ID,
        CURRENT_TIMESTAMP AS DW_CR_TMSP,
        v_MAPNG_ID AS UPD_BY_MAPNG_ID,
        CURRENT_TIMESTAMP AS DW_UPD_TMSP,
        v_WRK_FLOW_RUN_ID AS WRK_FLOW_RUN_ID
    FROM REF_TABLE
)
SELECT *
FROM audit_details
