{{ config(materialized='table') }}

SELECT *
FROM (
  SELECT
    REG_PER_YR AS reg_per_yr,
    FISC_PER_YR AS fisc_per_yr,
    NAIC_CMPNY_CD AS naic_cmpny_cd,
    LTRIM(RTRIM(ST_NM)) AS st_nm,
    LTRIM(RTRIM(ST_CD)) AS st_cd,
    LTRIM(RTRIM(ACCTNG_LOB)) AS acctng_lob,
    CVG_TYP_CD AS cvg_typ_cd,
    CVG_AMT AS cvg_amt,
    BI_LMT AS bi_lmt,
    GA_UMBI_PD_ADDED_IND AS ga_umbi_pd_added_ind,
    FA2_PLCY_IND AS fa2_plcy_ind,
    UM_UIM_STACKING AS um_uim_stacking,
    PIP_WVR_WL_IND AS pip_wvr_wl_ind,
    PIP_MED_SEC_IND AS pip_med_sec_ind,
    PIP_LOSS_INCOME_IND AS pip_loss_income_ind,
    MI_PPO_IND AS mi_ppo_ind,
    PRD_GRP_CD AS prd_grp_cd,
    NJ_HLTH_INSR_PRIM AS nj_hlth_insr_prim,
    NJ_EXTR_PIP_PKG AS nj_extr_pip_pkg,
    NJ_RESDNC_RLTNSHP_PIP_IND AS nj_resdnc_rltnshp_pip_ind,
    NY_SSL_IND AS ny_ssl_ind,
    NY_FULL_CVG_GLASS_COMP_IND AS ny_full_cvg_glass_comp_ind,
    NJ_NO_LWST_LMT_IND AS nj_no_lwst_lmt_ind,
    NJ_NMD_DRVR_EXCL_IND AS nj_nmd_drvr_excl_ind,
    GRGNG_ZIP_5 AS grgng_zip_5,
    RATNG_CMPNY_CD AS ratng_cmpny_cd,
    MLT_CAR_IND AS mlt_car_ind,
    RT_CLS AS rt_cls,
    AGE AS age,
    GENDR AS gendr,
    MRTL_STAT AS mrtl_stat,
    AUTO_USE_CD AS auto_use_cd,
    MILES_TO_WRK AS miles_to_wrk,
    GOOD_STDNT_IND AS good_stdnt_ind,
    DRVR_TRNG_IND AS drvr_trng_ind,
    SOI_TYP AS soi_typ,
    PHY_DMG_IND AS phy_dmg_ind,
    NJ_RTD_PNTS AS nj_rtd_pnts,
    VEH_MDL_YR AS veh_mdl_yr,
    NJ_EXCPTION_CD AS nj_excption_cd,
    NJ_FRGVN_PNTS AS nj_frgvn_pnts,
    PASSV_RESTRA_DISC AS passv_restra_disc,
    SNR_DRVR_IND AS snr_drvr_ind,
    DEFNS_DRVR_DISC_IND AS defns_drvr_disc_ind,
    ANTI_THFT_DISC AS anti_thft_disc,
    DAY_TM_RUN_LIGHTS AS day_tm_run_lights,
    LMT_TORT AS lmt_tort,
    CVG_TYP_IND AS cvg_typ_ind,
    CVG_EXPS_VAL AS cvg_exps_val,
    TTL_WRITTN_PREM_AMT AS ttl_writtn_prem_amt,
    COMP_DED AS comp_ded,
    COLL_DED AS coll_ded,
    LTRIM(RTRIM(PLCY_CNTRCT_NUM)) AS plcy_cntrct_num,
    UNIT_NUM AS unit_num,
    EFF_DT AS eff_dt,
    NUM_OF_CARS_IN_HH AS num_of_cars_in_hh,
    RDRVR_DT_OF_BRTH AS rdrvr_dt_of_brth,
    TERM_STRT_DT AS term_strt_dt,
    COALESCE(SRC_SYS_CD, '') AS src_sys_cd,
    PNI_AGE AS pni_age
  FROM {{ source('snowflake', 'fact_ag_writtn_prem_cvg_lvl') }}
) FETCH FIRST 1000 ROWS ONLY