{{
  config(materialized='ephemeral')
}}

WITH source_data AS (
  SELECT * FROM {{ source('source_system', 'table_name') }}
),

-- Node: LKP_RBI_REF_AUTO_TERR_ByStZipLob
LKP_RBI_REF_AUTO_TERR_ByStZipLob AS (
  SELECT
    *,
    CASE
      WHEN NISS_ST_CD = i_NISS_ST_CD AND ST_ABBRV = i_ST_ABBRV AND ZIP_CD = i_ZIP_CD AND PP_COMMRCL_CD = i_PP_COMMRCL_CD THEN 'MATCH'
      ELSE 'NO_MATCH'
    END AS lookup_result
  FROM source_data
),

-- Node: exp_ABC_MAPPING_AUDIT_ID_LOOKUP
exp_ABC_MAPPING_AUDIT_ID_LOOKUP AS (
  SELECT
    *,
    CASE
      WHEN v_RECORD_NUM = 1 THEN :LKP.lkp_MAP_ID(MAPPING_NAME, FOLDER_NAME)
      ELSE v_MAPNG_ID
    END AS v_MAPNG_ID
  FROM LKP_RBI_REF_AUTO_TERR_ByStZipLob
),

-- Node: EXPTRANS
EXPTRANS AS (
  SELECT
    *,
    FISC_PER_YR,
    NAIC_CMPNY_CD,
    NISS_CMPNY_CD,
    ST_NM,
    ST_CD,
    NISS_ST_CD,
    ST_ABBR,
    ACCTNG_LOB,
    CVG_TYP_CD,
    CVG_AMT,
    BI_LMT,
    GA_ADDED_AT_FAULT_IND,
    FA2_PLCY_IND,
    UM_UMI_STACKING,
    PIP_WVR_WL_IND,
    PIP_MED_SEC_IND,
    PIP_LOSS_INCOME_IND,
    MI_PPO_IND,
    PRD_GRP_CD,
    NJ_HLTH_INSR_PRIM,
    NJ_EXTR_PIP_PKG,
    NJ_RESDNC_RLTNSHP_PIP_IND,
    NY_SSL_IND,
    NY_FULL_CVG_GLASS_COMP_IND,
    GRGNG_ZIP_5,
    NISS_TERR_CD,
    RATNG_CMPY_CD,
    MLT_CAR_IND,
    RT_CLS,
    AGE,
    GENDR,
    MRTL_STAT,
    AUTO_USE_CD,
    MILES_TO_WRK,
    GOOD_STDNT_IND,
    DRVR_TRNG_IND,
    SOI_TYP,
    PHY_DMG_IND,
    NJ_RATD_PNTS,
    VEH_MDL_YR,
    NJ_EXCPTION_CD,
    NJ_FGVN_PNTS,
    PASSV_RESTRA_DISC,
    SNR_DRVR_IND,
    DEFNS_DRVR_DISC_IND,
    ANTI_THFT_DISC,
    DAY_TM_RUN_LIGHTS,
    LMT_TORT,
    ANNL_STMNT_LOB_CD,
    CVG_TYP_IND,
    CVG_EXPS_VAL,
    TTL_WRITTN_PREM_AMT,
    NJ_NO_LWST_LMT_IND,
    NJ_NMD_DRVR_EXCL_IND,
    COMP_DED,
    COLL_DED,
    PLCY_CNTRCT_NUM,
    UNIT_NUM,
    EFF_DT,
    NUM_OF_CARS_IN_HH,
    RDRVR_DT_OF_BRTH,
    TERM_STRT_DT,
    SRC_SYS_CD,
    PNI_AGE,
    MIS_LOB,
    PRINCIPAL_OPRT,
    SOURCE_IND_DERIVED,
    ANTI_THFT_CTGY_CD
  FROM exp_ABC_MAPPING_AUDIT_ID_LOOKUP
),

-- Node: EXP_PassThru_Tgt
EXP_PassThru_Tgt AS (
  SELECT
    *,
    v_CNT + 1 AS v_CNT,
    FISC_PER_YR,
    CALL_YR,
    NAIC_CMPNY_CD,
    NISS_CMPNY_CD,
    ST_NM,
    ST_CD,
    NISS_ST_CD,
    ST_ABBR,
    ACCTNG_LOB,
    CVG_TYP_CD,
    CVG_AMT,
    BI_LMT,
    GA_ADDED_AT_FAULT_IND,
    FA2_PLCY_IND,
    UM_UMI_STACKING,
    PIP_WVR_WL_IND,
    PIP_MED_SEC_IND,
    PIP_LOSS_INCOME_IND,
    MI_PPO_IND,
    PRD_GRP_CD,
    NJ_HLTH_INSR_PRIM,
    NJ_EXTR_PIP_PKG,
    NJ_RESDNC_RLTNSHP_PIP_IND,
    NY_SSL_IND,
    NY_FULL_CVG_GLASS_COMP_IND,
    GRGNG_ZIP_5,
    NISS_TERR_CD,
    RATNG_CMPY_CD,
    MLT_CAR_IND,
    RT_CLS,
    AGE,
    GENDR,
    MRTL_STAT,
    AUTO_USE_CD,
    MILES_TO_WRK,
    GOOD_STDNT_IND,
    DRVR_TRNG_IND,
    SOI_TYP,
    PHY_DMG_IND,
    NJ_RATD_PNTS,
    VEH_MDL_YR,
    NJ_EXCPTION_CD,
    NJ_FGVN_PNTS,
    PASSV_RESTRA_DISC,
    SNR_DRVR_IND,
    DEFNS_DRVR_DISC_IND,
    ANTI_THFT_DISC,
    DAY_TM_RUN_LIGHTS,
    LMT_TORT,
    ANNL_STMNT_LOB_CD,
    CVG_TYP_IND,
    CVG_EXPS_VAL,
    TTL_WRITTN_PREM_AMT,
    NJ_NO_LWST_LMT_IND,
    NJ_NMD_DRVR_EXCL_IND,
    COMP_DED,
    COLL_DED,
    PLCY_CNTRCT_NUM,
    UNIT_NUM,
    EFF_DT,
    NUM_OF_CARS_IN_HH,
    RDRVR_DT_OF_BRTH,
    TERM_STRT_DT,
    SRC_SYS_CD,
    PNI_AGE,
    MIS_LOB,
    PRINCIPAL_OPRT,
    SOURCE_IND_DERIVED,
    ANTI_THFT_CTGY_CD
  FROM EXPTRANS
)

SELECT * FROM EXP_PassThru_Tgt;