WITH farmers_state AS (
    SELECT
        FARMERS_STATE_CD,
        STATE_CODE
    FROM {{ source('FDR', 'REF_TFARMERS_STATE') }}
)
SELECT
    FARMERS_STATE_CD,
    CAST(FARMERS_STATE_CD AS INTEGER) AS IFARMERS_STATE_CD,
    STATE_CODE
FROM farmers_state
