{% macro mplt_CDM_BATCH_ID(source_name) %}
WITH lkp_CDM_BATCH_CTRLID AS (
  SELECT 
    MAX(BATCH_ID) AS BATCH_ID,
    TRIM(SOURCE_NAME) AS SOURCE_NAME
  FROM {{ source('CDM', 'CDM_BATCH_CTRLID') }}
  WHERE STATUS = 'RUNNING'
  GROUP BY SOURCE_NAME
),
exp_NULL_CHECK AS (
  SELECT
    CASE 
      WHEN lkp_CDM_BATCH_CTRLID.BATCH_ID IS NULL THEN -999
      ELSE lkp_CDM_BATCH_CTRLID.BATCH_ID
    END AS o_BATCH_ID,
    lkp_CDM_BATCH_CTRLID.SOURCE_NAME
  FROM lkp_CDM_BATCH_CTRLID
  WHERE lkp_CDM_BATCH_CTRLID.SOURCE_NAME = {{ source_name }}
)
SELECT 
  o_BATCH_ID,
  SOURCE_NAME
FROM exp_NULL_CHECK
{% endmacro %}