{{
  config(
    materialized='ephemeral'
  )
}}

WITH input_transformation AS (
  SELECT
    MAPPING_NAME,
    FOLDER_NAME,
    WORKFLOW_NAME
  FROM {{ source('genai_power_bi', 'ABC_BAL_ROW_COUNTS') }}
),

expression_transformation AS (
  SELECT
    MAPPING_NAME,
    FOLDER_NAME,
    WORKFLOW_NAME,
    ROW_NUMBER() OVER () AS v_RECORD_NUM,
    CASE 
      WHEN ROW_NUMBER() OVER () = 1 THEN (
        CASE 
          WHEN :LKP.lkp_MAP_ID(MAPPING_NAME, FOLDER_NAME) IS NOT NULL THEN :LKP.lkp_MAP_ID(MAPPING_NAME, FOLDER_NAME)
          ELSE NULL
        END
      )
      ELSE NULL
    END AS v_MAPNG_ID,
    CASE 
      WHEN ROW_NUMBER() OVER () = 1 THEN (
        CASE 
          WHEN :LKP.LKP_WORKFLOW_RUN_ID_ABC(WORKFLOW_NAME) IS NOT NULL THEN :LKP.LKP_WORKFLOW_RUN_ID_ABC(WORKFLOW_NAME)
          ELSE :LKP.lkp_WORKFLOW_RUN_ID(WORKFLOW_NAME)
        END
      )
      ELSE NULL
    END AS v_WRK_FLOW_RUN_ID,
    CASE 
      WHEN ROW_NUMBER() OVER () = 1 THEN :LKP.lkp_MAP_ID(MAPPING_NAME, FOLDER_NAME)
      ELSE NULL
    END AS CR_BY_MAPNG_ID,
    CURRENT_TIMESTAMP AS DW_CR_TMSP,
    CASE 
      WHEN ROW_NUMBER() OVER () = 1 THEN :LKP.lkp_MAP_ID(MAPPING_NAME, FOLDER_NAME)
      ELSE NULL
    END AS UPD_BY_MAPNG_ID,
    CURRENT_TIMESTAMP AS DW_UPD_TMSP,
    CASE 
      WHEN ROW_NUMBER() OVER () = 1 THEN (
        CASE 
          WHEN :LKP.LKP_WORKFLOW_RUN_ID_ABC(WORKFLOW_NAME) IS NOT NULL THEN :LKP.LKP_WORKFLOW_RUN_ID_ABC(WORKFLOW_NAME)
          ELSE :LKP.lkp_WORKFLOW_RUN_ID(WORKFLOW_NAME)
        END
      )
      ELSE NULL
    END AS WRK_FLOW_RUN_ID
  FROM input_transformation
)

SELECT 
  MAPPING_NAME,
  FOLDER_NAME,
  WORKFLOW_NAME,
  CR_BY_MAPNG_ID,
  DW_CR_TMSP,
  UPD_BY_MAPNG_ID,
  DW_UPD_TMSP,
  WRK_FLOW_RUN_ID
FROM expression_transformation