-- Purpose: Map POLICY_STATE to INTEGRATION_ID
SELECT 
  POLICY_STATE, 
  CASE 
    WHEN POLICY_STATE = 'CA' THEN 'CA_INTEGRATION'
    WHEN POLICY_STATE = 'NY' THEN 'NY_INTEGRATION'
    ELSE 'OTHER_INTEGRATION'
  END AS INTEGRATION_ID
FROM 
  {{ ref('int_CDH_GW_BUR') }}